nodejs/nodejs.dev

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- ModerationPolicy.md
References foundation default CoC and Moderation policy.
CONTRIBUTING.md outlines basic governance for landing code changes.
TL;DR
* all changes require a PR and review from one other individual
* anyone from @nodejs/website or @nodejs/website-redesign can approve
> docs: Add initial governance.

- README.md
Yarn doesn't ship with Node.js.
> Add optional step to install Yarn

- package.json
- yarn.lock
Fixes #55 
Since we are already using react 16.8, react-dom@16.8 makes sense and also enables Hooks and Suspense.
> feat: Update react-dom to enable hooks.

- .github/action/result-poster/index.js
Hello! Awesome to see you using [actions-toolkit](https://github.com/JasonEtco/actions-toolkit) for an action here. Thought I'd pop in with some semantic improvements, as well as a newly added feature that'd help make the action a tad bit more reliable.
* Added the `event` option in the Toolkit constructor - this feature [was added in 1.4.0](https://github.com/JasonEtco/actions-toolkit/releases/tag/v1.4.0) and will skip the action if the event trigger doesn't match. Just ensures that your action isn't being triggered by the wrong event.
* Replaced `request` with `issues.createComment` - that way you don't need to remember the API endpoint 👌 it's a little more clear whats happening.
Feel free to dismiss if you don't think these changes are necessary of course 🇨🇦
> Improve actions-toolkit usage

- .gitignore
- package.json
- test-preprocessor.js
- test-setup.js
- test/__mocks__/fileMock.js
- test/__mocks__/gatsby.js
- test/components/__snapshots__/header.test.tsx.snap
- test/components/header.test.tsx
- yarn.lock
My thoughts about #59. Note that since [ts-jest and babel-jest@24 do not play well together](https://github.com/facebook/jest/issues/7868) `@babel/preset-typescript` is used as a workaround.
> chore: Add testing framework.

- gatsby-node.js
- src/pages/learn.tsx
- src/util/createSlug.js
This PR moves slug generation to `gatsby-node.js` which makes it possible to query the slug later on. It also attempts to make the slug generation process a bit more robust, taking into account that we might want to customize this for other languages in the future.
Ps: should probably add some tests for this once we have a test runner set up
> feat: Improve slug generation.

- src/documentation/0006-v8/index.md
Fixes a typo in https://nodejs.dev/learn/the-v8-javascript-engine
> Compilation: Fix typo "JavScript"

- package.json
Minor fix, updates the repository url in package.json to point to this repo instead of gatsby-starter-default
> docs: Update repository url.

- src/components/layout.css
- src/components/mobile.css
- src/pages/learn.tsx
Inverted slant to save room, becomes sticky higher up, make white top nav smaller.
Vertical offset for page content is within ~10px of change made in #76 without looking a little jank, and includes improvements for tablet and mobile 👍
> fix: Improve the header to take up less space.

- .travis.yml
This will ensure we don't have the test suite pass when it the build
itself is broken.
Refs: https://github.com/nodejs/nodejs.dev/pull/61
> build: Run `yarn build` in travis.

- src/components/article.tsx
- src/components/edit-link.tsx
- src/components/hero.tsx
- src/components/navigation-item.tsx
- src/components/navigation-section.tsx
- src/components/navigation.tsx
- src/components/pagination.tsx
- src/documentation/0001-node-introduction/index.md
- src/documentation/0002-node-history/index.md
- src/documentation/0003-node-installation/index.md
- src/documentation/0004-node-javascript-language/index.md
- src/documentation/0005-node-difference-browser/index.md
- src/pages/learn.tsx
- src/types/index.ts
- src/util/findActive.ts
Rather extensive but all changes felt related.
- Split components/page into smaller chunks that will make it less painful to merge changes in the future
- The navigation now lives in its own component(s) that handle state for toggling the menu on mobile devices
- Generates nav sections from frontmatter fields
- magicHeroNumber handled inside of component when rendered
> refactor: Split components into smaller pieces.

- src/components/mobile.css
Fixes #102.
One less than ideal result is that on open the scrollbar appears immediately while the side nav transforms out. There are probably ways to handle that but I'm not sure it's worth the effort.
Chrome with side nav closed doesn't show scrollbar:
With side nav open, scrollbar is shown:
> style: Only show side-nav scrollbar when open.

- src/components/layout.css
This happens because the hero section has set width: `100vw`, using `100%` instead. Some browsers do not include the scroll bar width to `100vw` so `100vw` exceeds the width of the browser when have a scroll bar on the right.
Close: #112
> Remove scroll by x

- src/components/header.tsx
- src/components/layout.css
- src/components/mobile.css
- test/components/__snapshots__/header.test.tsx.snap
Use `line-height` instead of `padding` is a better way.
Close: #114
> style: Vertical align middle for top nav.

- src/pages/learn.tsx
This PR fixes the homepage title which is displayed wrong on social media and search engines.
Instead of the info about our first post, Node.js site's default title and description should be displayed.
Looking forward, peace! ✌️
/gcbrun
> fix: Homepage SEO Title & Description.

- package.json
Husky is currently giving us a deprecation warning to move `commit-msg` out of `package.scripts`. Used auto update tool. Husky still runs and no more warnings 🎉
> build: Fix husky warning.

- CONTRIBUTING.md
Reference from our core repo `nodejs/node`: [commit-message-guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)
> be prefixed with the name of the changed subsystem and start with an imperative verb. Check the output of `git log --oneline files/you/changed` to find out what subsystems your changes touch.
Refs: #134
> docs: Harden commit message in Commit Guidelines.

- src/util/createSlug.js
While checking out `util/createSlug.js`, my IDE warned about a couple of trivial improvement opportunities for two simple regular expressions in `util/createSlug.js`.
Took a stab to simplify the warned regular expressions. Tested in local comparing the page title (and nav item name to the parsed URL slug. Looked okay. Will test in staging more. 🙏
> refactor: Update regular expression in util/createSlug.js.

- .prettierrc
- CONTRIBUTING.md
- commitlint.config.js
- Update commitlint config to disallow period at the end of a commit
message
- Document this decision in CONTRIBUTING.md and add a link to the
Conventional Commits specification
Refs: https://www.conventionalcommits.org/
Fixes: https://github.com/nodejs/nodejs.dev/issues/150
> feat: Update commitlint config and docs to disallow a period at the end

- src/components/layout.css
- src/components/layout.tsx
- src/components/mobile.css
This might need a bit of tweaking so consider it a WIP. 
The idea is that instead of calculating the hero offset in each animation frame - we can use the IntersectionObserver API. We are notified each time the intersection changes and when a `.side-nav__title` intersects with the hero banner, we apply some white color. Should offer some performance benefits and might also help solve #86.
Seems like the [browser support is pretty good](https://caniuse.com/#feat=intersectionobserver), so this should work out of the box in most browsers. What are your thoughts on this?
> refactor: Use IntersectionObserver in Layout component

- .prettierignore
- package.json
- src/components/article.tsx
- src/components/hero.tsx
- src/components/navigation-item.tsx
- src/components/pagination.tsx
- src/components/seo.tsx
- src/config.js
- src/pages/404.tsx
- src/util/createSlug.js
- src/util/scrollTo.tsx
- test-setup.js
- test/components/author-link.test.tsx
- test/components/header.test.tsx
- test/components/hero.test.tsx
- test/components/seo.test.tsx
- test/util/createSlug.test.js
- test/util/onCreateNode.test.js
- tslint.json
- yarn.lock
- Bump prettier version to 1.16.4
- Add `format-check` and `tslint` scripts to package.json
- Run `format-check` and `tslint` scripts in Travis CI
Running `yarn format-check` will currently fail with exit code 1 since a bunch of files aren't formatted correctly (this is what's causing the build for this PR to fail). Once we have decided on some formatting rules (#90) and the project is formatted in a unform way, this will work as a guard for not merging code that isn't correctly formatted or that is missing type annotations etc.
> chore: Run prettier/tslint in ci

- .prettierignore
Adding coverage directory to `.prettierignore` (a few files in the coverage directory causes `format-check` to fail)
> chore: Add coverage directory to .prettierignore

- package.json
* Add format-check and tslint scripts in pre-push hook
* Remove unneeded keyword "run" in `yarn` commands of the `test` npm-run script
* Correct `test` script to run `format-check` and `tslin`, before `jest` to avoid snapshot update flag (`-u`) not being supported by `tslint` script:
```sh
$ tslint --project ./tsconfig.json -u
error: unknown option `-u'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Fixes #164
> chore: Add format-check and tslint scripts in pre-push hook

- src/components/layout.tsx
- src/components/navigation-section.tsx
- src/components/navigation.tsx
- src/types/index.ts
Use a flattened data structure (`flatSessions`) to determine `isDone` flags for each navigation item, based on the index of the active slug.
Fixes #176
> fix: Correct logic to mark nav items done

- src/components/layout.css
- src/components/layout.tsx
- src/components/mobile.css
Fix for FF: switched to using `intersectionRatio` instead of `isIntersecting` to detect intersection of the target with specified root (`isIntersecting` is apparently buggy and inconsistent across browsers, and therefore not reliable).
Fix for older browsers like Safari 12: apply custom CSS on the presence of `[data-browser=legacy]`. Set `[data-browser=legacy]` during the first invocation of the side-effect function `magicHeroNumber`.
Fixes: https://github.com/nodejs/nodejs.dev/issues/184
> fix: Navigation title color in FF and legacy browsers

- src/components/mobile.css
Fixes the behaviour where long-ish menu items previously bled through the side navigation title.
Fixes: https://github.com/nodejs/nodejs.dev/issues/190
> fix: Avoid side nav menu items bleeding through the title

- src/documentation/0006-v8/index.md
1. I have attempted to link the references of other JavaScript Engines with their respective documentation or GitHub Links. Just like how it was previously done with SpiderMonkey
2. Spidermonkey is referenced as `SpiderMonkey` in the MDN docs for the same, so I have attempted to change it in the article here.
Have not created an issue for the same, as I felt that this PR is attempting simple changes.
> Docs: Fixed SpiderMonkey reference and added links to other JavaScript engines referenced. 

- src/components/mobile.css
While reviewing `mobile.css`, found the `TODO` note about setting max height based on content.
Tried a fix to address this TODO by using `100%` to set the max height the height of the viewport. 
N/A
> style: Set max-height to 100% in mobile.css

- src/components/authors-list.tsx
- src/components/edit-link.tsx
- src/components/pagination.tsx
- test/components/__snapshots__/authors-list.test.tsx.snap
- test/components/__snapshots__/edit-link.test.tsx.snap
- test/components/__snapshots__/pagination.test.tsx.snap
This is one of my favorite PRs — since the inconsistent styles for the footer area of docs were eating up on me. So, here it goes. GUI representation first. 💯
---
As you can see this PR adds the following things:
/gcbrun
> feat: Edit links with SVG Icons & Consistent styles for Pagination/Contributors

- .travis.yml
- package.json
- yarn.lock
This PR enables reporting code coverage during Travis builds. ~~To get this up and running, someone with admin access needs to login to [Coveralls](https://coveralls.io/) and add this repo.~~ (using codecov)
#206
> chore: Report coverage during travis builds

- src/components/layout.css
Small style change to remove the blue outline that appears when opening or closing the `TABLE OF CONTENTS` dropdown.
> style: Remove toc outline on focus

- src/components/author.tsx
- src/components/authors-list.tsx
- src/components/edit-link.tsx
Improve type for  emotion css props in code w. `SerializedStyles` (similar to pagination.tsx):
https://github.com/nodejs/nodejs.dev/blob/e47be96332301101bc66b4422defeaeb37f339ed/src/components/pagination.tsx#L6
N/A
> refactor: Use SerializedStyles type for css props

- src/components/toc.tsx
- src/documentation/0032-javascript-timers/index.md
- src/documentation/0034-javascript-promises/index.md
- src/util/tocFormatter.ts
There's a [bug in Gatsby](https://github.com/gatsbyjs/gatsby/issues/8982) such that Table of Content links with code tags inside of them aren't sanitized properly. We can see this bug on several of our pages:
https://nodejs.dev/the-nodejs-path-module
https://nodejs.dev/the-nodejs-os-module
https://nodejs.dev/the-nodejs-events-module
https://nodejs.dev/the-nodejs-http-module
This PR is a fix for Gatsby's issue so our pages can display code in TOC links properly:
https://github.com/nodejs/nodejs.dev/issues/212
> Fix TOC links for HTML code tags

- package.json
- src/components/layout.tsx
- src/templates/learn.tsx
- yarn.lock
After researching polyfill for `IntersectionObserver`, trying out the [`intersection-observer` polyfill from w3c](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) in this PR.
Navigation Title color looks okay in local testing with the XCode iOS Simulator (usually pretty native to real iPhone). Looking forward to review & testing more in staging.
Fixes #207
> feat: Use intersection-observer polyfill to support IntersectionObserver

- src/documentation/0036-node-event-emitter/index.md
We should consider using `new` keyword to properly instantiate EventEmitter class object, otherwise we get an error (as per current docs example):
```js
const eventEmitter = require('events').EventEmitter()
eventEmitter.on('start', () => {
console.log('started')
})
```
ends up with:
```
TypeError: Cannot read property 'on' of undefined
```
Whereas instantiating with `new`:
```js
const EventEmitter = require('events')                                          
const eventEmitter = new EventEmitter()
console.log(eventEmitter instanceof EventEmitter) // true
eventEmitter.on('start', () => {
console.log('started')
})
eventEmitter.emit('start')
```
outputs:
```
true
started
```
Fixes #242
> docs: Fix EventEmitter initialization example

- src/components/layout.css
- src/components/layout.tsx
- src/util/outlineOnKeyboardNav.ts
- test/util/outlineOnKeyboardNav.test.js
This PR partially reverts the changes made in #224 to [comply with a11y on outlines](https://a11yproject.com/posts/never-remove-css-outlines/). 
Outlines will display during keyboard navigation (ex. tabbing) and will hide on mouse clicks.
Outlines have also been styled using nodejs.dev's brand colors, for better visual appeal.
**vs.**
Resolves #239
> Show outline on keyboard nav and style outline to match theme

- src/components/navigation.tsx
- src/util/scrollTo.tsx
Ran into these IDE warning and gave an attempt to refactor to address the best I could. Sanity tested locally. Looking forward to more sanity test in staging and your review. Thanks.
* returned value is indeed a promise from `scrollTo` function; use `async` / `await` to resolve promise with `try` / `catch` for error scenario
* local variant `ret` in `scrollTo` function could be simplified
* since the promise is always resolving `true` as successful scenario, it seems safe to omit `return` statement, in interest to avoid such nit by code analysis in IDE(s) (e.g. Webstorms)
N/A
> Refactor to resolve the returned promise from scrollTo function

- src/documentation/0013-node-output-to-cli/index.md
Fixes #241 
Previous link was 404 because users seems to change his github handle
> docs: Fix link in docs

- .github/action/result-poster/package-lock.json
- .github/action/result-poster/package.json
- .travis.yml
- gatsby-config.js
- yarn.lock
Upgrade dependencies in .github/action/result-poster/package.json to
quell several (but not all) `npm audit` warnings.
(gatsby-config.js needed prettier run on it, so that's why it's
modified. Guess someone committed something while bypassing the prettier
checks?)
> chore: Upgrade dependencies

- package.json
- yarn.lock
Update gatsby from 2.0.91 to 2.13.13. This updates dependencies
includeing eliminating dependency on lodash.merge, which previously had
a vulnerable version in the yarn.lock file.
> chore: Update gatsby

- src/documentation/0010-node-hosting/index.md
Fixed the branding for ZEIT Now to use the correct uppercase branding.
https://zeit.co/now
> Fix typo ZEIT Now

- src/documentation/0001-node-introduction/index.md
> docs: be "Node.js" case sensitive

- src/documentation/0001-node-introduction/index.md
The number 500,000 is severely outdated by now.
> docs: Tweak number of npm packages available

- cloudbuild-deploy.yaml
- cloudbuild.yaml
currently we use the GCR images which don't allow us to specify node versions. This improves that.
> build: replace gcr images w/ official images

- src/documentation/0006-v8/index.md
add link to [V8 website](https://v8.dev/) and [Standard ECMA-262](https://www.ecma-international.org/publications/standards/Ecma-262.htm)
to go directly to the site, without having to search the web
> doc: add link to V8 and Standard ECMA-262

- .remarkrc
- package.json
- yarn.lock
Although it was a point release, it actually added/aligned the preset with the "recommended" preset for remark-lint.
This will likely conflict a little with #351, but whichever lands first, the other can be rebased
> chore: bump remark-preset-lint-node to 1.10.1

- src/documentation/0052-nodejs-streams/index.md
stream.Readable examples on https://nodejs.dev/nodejs-streams cannot run and error `Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented` occurs. 
This PR fixes the examples to run them correctly. They need `readableStream._read = () => {}`. According to [api doc for `readable._read`](https://nodejs.org/api/stream.html#stream_readable_read_size_1), `_read()` must be implemented in all readable stream.
> All Readable stream implementations must provide an implementation of the readable._read() method to fetch data from the underlying resource.
Fix #365
> fix: Stream.Readable example

- src/components/controls.tsx
- src/components/header.tsx
- src/components/hero.tsx
- src/components/layout.tsx
- src/pages/index.tsx
This PR addresses #408 for the linting warnings.
> refactor(linting warnings): Fixed linting warnings

- src/components/banner.tsx
- test/components/__snapshots__/banner.test.tsx.snap
The button is receiving the style from each browser user agent stylesheet.
- Chrome:
- Safari:
By styling the border button, the button will be able to look exactly the same:
- Chrome:
- Safari:
Fixes #422
> Fix(banner.tsx): Set border property

- package.json
- yarn.lock
Using `@smotaal.io/dark-mode-controller` to `<0.5` is preferred in this case since this package is authored primarily for this project and is going through lots of changes under the hood that affect other projects.
> **Note** — Version range `^0.0.4` did not pick up `v0.0.5` in development when `v0.0.4` was already cached by `yarn` even when the `yarn.lock` entry was removed (issue pending).
**`Mar11`** https://storage.googleapis.com/staging.nodejs.dev/0b662e0/index.html 
Relates to #336.
> build: Switch dark-mode-controller to <0.5

- src/pages/index.tsx
- src/styles/index.css
This PR removes the mailing list section of the hompage.
The mailing list for nodejs hasn't been published in many months.
Closes https://github.com/nodejs/nodejs.dev/issues/331
> fix(homepage): Removed mailing list signup

- src/documentation/0010-node-hosting/index.md
The old link https://serverless.com/framework/ has 404 Not Found.
> fix: Broken link in index.md

- .github/action/result-poster/index.js
- .github/action/result-poster/package.json
- .github/workflows/result-poster-ci.yml
Add an Action to test the action ....
This really just runs the linting, and makes sure the install can run
> build: Add CI for Result Poster Action

- cloudbuild-staging.yaml
This should have 0 affect on master but will make eventually reconciling staging with master easier. Cherrypicking the single unique commit from https://github.com/nodejs/nodejs.dev/pull/661
> tools: automate deployment of staging branch

- src/documentation/0054-node-exceptions/index.md
Tweaked function calls in examples in "Exceptions with promises" section to reduce possible confusion vectors: 
1. `doSomething1` is a function that returns a `Promise` in both examples
2. `doSomething2` and `doSomething3` should not be called until the `doSomething1` promise resolves if they return a `Promise` or the chain will be broken.
3. In examples of mid-chain handling, there is an extra parenthesis in first `then`
This will result in correct order: AA (after 2s) -> BB (after 3s)
````
new Promise(
(r, j) => setTimeout(() => {
console.log("AA");
r();
}, 2000)
).then(
() => new Promise(
(r, j) => setTimeout(() => {
console.log("BB");
r();
}, 1000)
)
);
````
But this won't (as promise is scheduled immediately): BB (after 1s) -> AA (after 2s)
````
new Promise(
(r, j) => setTimeout(() …
```
> docs: Fix Promise error handling examples

- README.md
- package-lock.json
- package.json
- src/components/installTabs.tsx
- src/pages/index.tsx
- src/styles/install-tabs.scss
- test/components/__snapshots__/installTabs.test.tsx.snap
- test/components/installTabs.test.tsx
This PR is for the install tabs on the homepage. See my demo link
~~https://install-tabs--staging-nodejsdev.netlify.app/~~
https://staging.nodejs.dev/612/
I think we want the most popular Operating systems displayed and not what we see in the design. 
Outside of Mac OS, Windows and Ubuntu what else should be included. We can fit 5 
For reference 
Where should the read documentation button go? Right now my PR does not include this button.
#333
> Install tabs on homepage

- src/components/installTabs.tsx
- src/styles/index.scss
- src/styles/install-tabs.scss
- test/components/__snapshots__/installTabs.test.tsx.snap
Styling improves of Install tabs 
Addresses  #719
Before
After
> style: Update styles for intall-tabs

- .prettierrc
- package.json
- src/components/Hero/Hero.scss
- src/components/InstallTabs/InstallTabs.scss
- src/pages/index.tsx
- src/styles/index.scss
This PR is my attempt to make the buttons a bit more consistent and especially accessible as per the WCAG2.0 contract guidelines of min AA color contrast.
Fix #743 #745 #746 #748
There were also a couple of minor issues like the `.prettierrc` file had wrong syntax and typescript dev/devDeps version conflicts that I fixed within this PR. Otherwise, the local dev would not start or format the files.
> fix: Buttons consistency

- src/documentation/0023-update-npm-dependencies/index.md
If 'npm' is a singular subject than wants is used instead of want.
Grammar change to the explanation of 'npm update'. This is should be changed if npm is being used as a singular subject. I know it is minor but figured I could point it out and practice a pull request. :)
> Grammar change for want/wants

- src/documentation/0040b-node-file-descriptors/index.md
`..., which instead of providing the file descriptor object in a callback, it returns it:` - does not look like correct sentence. Maybe this change would make it more clear.
> Update sentence for fs.openSync

- src/styles/index.scss
This PR fixes janky scrolling by removing filter drop-shadow CSS property. 
`Note:` Even after removing drop-shadow i didn't see any significant change in animation or difference in UI.
**Difference**:
`Existing:` https://nodejs.dev
`Staging`: https://staging.nodejs.dev/771/
Fixes #770
> Fix: Janky scrolling of filter drop-shadow

- src/components/Footer/footer.scss
- src/components/Footer/index.tsx
- src/styles/layout.scss
This helps cleanup issues from [721](https://github.com/nodejs/nodejs.dev/issues/721)
* Moved footer styles from `layout.scss` into `src/components/Footer/footer.scss` making it easier for developers to find it when needed to adjust or add more styles.
> Moves footer scss from layout to component folder

- src/components/InstallTabs/InstallTabs.scss
Looks like the CSS for this button hover was not working correctly. This adds correctly hover functionality that matches the same pink color used in the shell box.
> Style: Add hover style to shell box documentation button

- src/styles/learn.scss
Fixes #780 
If side navigation is scrolled when user changes window size to mobile, the contents of the navigation show behind the hamburger button.
This PR reduces the height of the nav__list until the side nav is open.
> hide mobile navigation until menu is  open

- src/pages/404.tsx
- src/pages/docs.tsx
- src/pages/download.tsx
- src/pages/index.tsx
- src/pages/style-guide.tsx
- src/styles/layout.scss
- src/templates/learn.tsx
- test/pages/__snapshots__/404.test.tsx.snap
- test/templates/__snapshots__/learn.test.tsx.snap
Hello there! 😅
I noticed that a couple pages on the site are not wrapped in a [`<main>` sectioning element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main), so the goal of this PR is to ensure that each page includes this semantic markup.
**The `<main>` landmark element is part of the [WCAG 2.0 checkpoint: 4.2.1 - Name, Role, Value](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)**, and it improves accessibility of a page by [helping assistive tech quickly identify the primary content of the page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#Accessibility_concerns).
Also, I noticed that 2 pages -- the 404 page and the [Download page](https://nodejs.dev/download/) -- were specifically using `<article>` elements to wrap page content; in …
> Ensure that primary page content is wrapped in <main> for accessibility

- src/pages/docs.tsx
- src/styles/layout.scss
The [Docs page](https://nodejs.dev/docs/) has an API version `<select>` form control that is missing a corresponding `<label>`, so it is missing important context about what the form control does and means.
I suggest adding a `<label>` following [WCAG 2.0 guidance on form controls](https://www.w3.org/TR/WCAG20-TECHS/H44).
To make this happen, I made two other related changes:
**Visually hide the `<label>` with new `.visually-hidden` utility class.**
- [The A11yProject has tips for hiding content so it's still detectable by a screen reader](https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/). The PR adds a `.visually-hidden` utility class that keeps the `<label>` in the DOM .
- Generally I think it's ideal to show form control `<label>`s (not hide visually hide them), but …
> Add label to API version select form control on Docs page

- CONTRIBUTING.md
- cloudbuild-staging.yaml
The staging branch is no longer used for feature development. It's only purpose is for when a developer creates a pull request preview by doing `/preview`
> docs(contributing.md) removed staging note.

- .github/workflows/cleanup-staging.yml
When a PR is merged or closed this should cleanup the files from the Google Storage that hosts the staging site. 
Closes #636
Looked at https://cloud.google.com/storage/docs/gsutil/commands/rm but wasn't sure if the `-m` and `-f` flags would be required for this or not
> chore: GH Action to clean closed/merged previews

- .github/workflows/cleanup-staging.yml
Force to avoid failed build for non-previewed PRs
Should speedup the cleanup by running in parallel, and avoid false failures for PRs closed with no previews
> chore: Run PR cleanup in parallel with force

- .github/workflows/start-ci.yml
> chore: Convert preview to use labels

- README.md
fixes the (still) broken figma link. the other PR that did this apparently didn't actually fix it.
> fix: figma link (again)

- src/documentation/0002-node-history/index.md
Added Node.js releases for years 2019 and 2020
I was reading over the history of Node.js and found that 2019 and 2020 were not included so I decided to add them
> Updated node-history index.md

- src/styles/layout.scss
Currently, the "active"/current nav item has the same green underline styling as the nav item `:hover` state. (Side note: personally I think these styles should be different.)
As shown in #887, at mobile breakpoints there is no spacing between navigation tabs in the header. So, depending on which page you are currently on, hovering over another nav item make it appear as if the "active" nav item's underline is connected to the underline for the nav item you are hovering over.
This PR adds `margin-right: 0.5rem` to nav items at the mobile breakpoint (excluding the `:last-child`). The reason I opted for `margin-right`, instead of `margin-left`, is because the nav items' container already has a `margin-left` applied, so going with `margin-right` is less disruptive to the layout. 👍 …
> Add margin-right to nav tabs on mobile

- src/styles/layout.scss
Follow up to this conversation: https://github.com/nodejs/nodejs.dev/issues/887#issuecomment-675724363
And this: https://github.com/nodejs/nodejs.dev/pull/888#pullrequestreview-469897668
This PR updates the color of the primary nav border whenever you hover over a nav item. As discussed in https://github.com/nodejs/nodejs.dev/issues/887#issuecomment-675724363, currently the hover color and the "active" or current page color are the same.
Ideally hover states should have a border of some kind, rather than just relying on color alone (source: [WCAG 2.0 - 1.4.1 Use of Color](https://www.w3.org/TR/WCAG20/#visual-audio-contrast-without-color). So considering that, I didn't want to just remove the border for hover states. Instead, I have opted to keep the hover border & update the color: …
> Update hover border color for header nav items

- src/components/InstallTabs/__tests__/__snapshots__/index.js.snap
- src/components/InstallTabs/index.tsx
Changed it so that the operating system of the user is displayed before the package manager 
i.e: nvm (macOS) => macOS (nvm)
Also show zsh instead of bash as the default shell header if the user is using macOS, since as of Catalina zsh has replaced bash as macOS's default terminal shell.
> style: Install Tabs text changes

- src/components/InstallTabs/InstallTabs.scss
- src/components/InstallTabs/LinuxPanel/index.tsx
- src/components/InstallTabs/MacOSPanel/index.tsx
- src/components/InstallTabs/WindowsPanel/index.tsx
- src/components/InstallTabs/__tests__/__snapshots__/index.js.snap
No visual changes were made. The "Read documentation" button was a `button` with an `a` inside. This reduces the hit area of the button that results in an action (opening the documentation) only the text bounds.
The fix is to apply the button styles directly to the `a`. This PR also makes keyboard/AT navigation a lot better, an accessibility win!
This PR also updates the button's styles to match the mockup in Figma.
> Fix: Make documentation button hit area the whole button in Shell box

- src/pages/sites/metrics.mdx
A PR to add the node.js metrics page. The new url is `/sites/metrics`. Uses mdx, which later on can be customised to use React components and make the graphs interactive. I used the existing markdown from [here](https://raw.githubusercontent.com/nodejs/build/e3a4a86ab447084e17b740deceb7eab39faaadff/ansible/www-standalone/tools/metrics/public-index.md)
Replaces https://nodejs.org/metrics/
Addresses issue #885 
Tracking issue #275
> Add Node.js metrics microsite

- src/documentation/0029-node-event-loop/index.md
A small grammatical correction to an otherwise perfect explanation
In the learn page, under Message Queue in the Node.js Event loop section, it says "When setTimeout() is called, the Browser or Node.js **start** the timer". It has been changed to **starts** to make it grammatically correct.
> docs: Changed "Node.js start the timer" to "starts"

- src/pages/index.tsx
- src/styles/index.scss
Adds `prefers-reduced-motion` media query for the leaves animation to help with accessibility. Tested on Firefox and Google Chrome after disabling Settings > Ease of Access Display Settings > **Show animations on Windows**. 
Addresses #964
> Added prefers-reduced-motion media query for accessibility

- src/components/DownloadHeader/DownloadHeader.scss
- src/components/InstallTabs/InstallTabs.scss
This PR changes the font color of Downloads header in Dark mode and the fonts in inactive tabs in light mode.
Addresses #971
> Changed font color for Downloads header and tabs , Resolves #971

- src/components/Footer/footer.scss
- src/components/Layout/index.tsx
- src/pages/docs.tsx
- src/styles/layout.scss
This PR makes the footer stick to the bottom of the viewport when the content is less than the viewport height. When the content is greater than the viewport height, the footer will be right below the content.
Addresses #972
- Large main content (`/download`)
- Small main content (`/404`)
- `Header` is always at the top of the viewport with/without scrolling
- `/docs`
> Makes the footer stick to the bottom of the viewport

- src/templates/learn.tsx
- test/templates/__snapshots__/learn.test.tsx.snap
Main content frame is empty and header doesn't fill up the parent width(100%) in the Learn Page because the main tag is nested outside the Layout. Done fixing it and made sure it doesn't break anything else (including the mobile view). 
Addresses #982 & #983.
> Fix: Learn Page Layout

- gatsby-config.js
The images in `/learn` has a white background even in the dark mode when ideally it should be transparent.
How it looks currently in Dark Mode:
How it looks in the PR
None
> fix: Image background in remark-images

- src/components/InstallTabs/InstallTabs.scss
Improves colour contrast between tab background and 'read documentation' button to [WCAG 2 AA compliance](https://snook.ca/technical/colour_contrast/colour.html#fg=D9E1E4,bg=2C3437).
I used the background colour of the 'SHELL' block, so hopefully that will keep the theme intact.
Resolves: #993
> fix(InstallTabs): docs button to WCAG2 AA contrast

- src/components/DownloadCards/__tests__/__snapshots__/download-cards.test.tsx.snap
- src/components/DownloadCards/index.tsx
- src/components/DownloadToggle/DownloadToggle.scss
- src/components/DownloadToggle/__tests__/__snapshots__/download-toggle.test.tsx.snap
- src/components/DownloadToggle/index.tsx
Improves a11y on downloads page by:
- Replacing two-button LTS/Current with aria-check implementing toggle
- Adding keyboard navigation to select distro
Resolves #996
> fix(releases-page): download selection a11y

- src/components/DownloadHeader/DownloadHeader.scss
- src/styles/layout.scss
- src/styles/tokens.scss
I started the PR by changing the `font-size` to 1.2rem which would mantain the color structure of the page, but [the size must be 18pt+](https://snook.ca/technical/colour_contrast/colour.html#fg=6E7B83,bg=FFFFFF).
So, in order to be [fully compliant](https://snook.ca/technical/colour_contrast/colour.html#fg=2C3437,bg=FFFFFF), I changed the color to use the primary text one.
fixes #995
> chore(styles): breadcrumb a11y compliant

- src/styles/layout.scss
@media (max-width: 800px)
.nav__tabs > a
Currently using "--space-10" for padding which is undefined. Changed to "--space-08"
Fixes #1008 Increase the spacing for main navigation links on mobile
> Fix: mobile padding variable undefined #1008

- src/documentation/0001-node-introduction/index.md
- src/documentation/0013-node-output-to-cli/index.md
- src/documentation/0029-node-event-loop/index.md
- src/documentation/0034-javascript-promises/index.md
- src/documentation/0035-javascript-async-await/index.md
- src/documentation/0037-node-http-server/index.md
This PR adds the title attribute to the embed iframe and removes `allow="geolocation; microphone; camera; midi; encrypted-media"` boilerplate from glitch.
Closes #1004
> docs(docs): Added title to iframe for a11y

- src/components/DownloadReleases/DownloadReleases.scss
- src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
- src/components/DownloadReleases/index.tsx
- src/components/InstallTabs/InstallTabs.scss
- src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
- src/components/InstallTabs/index.tsx
- src/components/UpcomingReleases/UpcomingReleases.scss
- src/components/UpcomingReleases/UpcomingReleasesItem/UpcomingReleasesItem.scss
- src/components/UpcomingReleases/UpcomingReleasesItem/index.tsx
- src/components/UpcomingReleases/UpcomingReleasesPanel/index.tsx
- src/components/UpcomingReleases/__tests__/__snapshots__/upcoming-releases.test.tsx.snap
- src/components/UpcomingReleases/__tests__/upcoming-releases.test.tsx
- src/components/UpcomingReleases/index.tsx
- src/components/UpcomingReleases/upcomingReleases.ts
This pr change the look and feel of tabs on "upcoming releases" section according to #987.
Notes:
- I add a parent div(with classname) to the `installTabs` component. So, it isolate the css properties / rules of "react-tab".  Without this prefix, the `installTabs` css rules affected the entire app.
- I moved the upcoming releases data to a separate file. So now the data does not depend on the UI/React code. Furthermore, it helps to reuse code so I created` UpcomingReleasesItem` component.
Related to #987
> feat: upcoming releases tabs

- gatsby-config.js
This option does not exist anywhere in the `gatsby-source-filesystem` codebase and does not do anything. Submitting this PR now to ensure your website won't break once we introduce plugin option validation! :pray:
N/A
> Remove invalid gatsby-source-filesystem "include" option

- src/components/DownloadReleases/DownloadReleases.scss
- src/components/DownloadReleases/DownloadTable.scss
- src/components/DownloadReleases/DownloadTable.tsx
- src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
- src/components/DownloadReleases/__tests__/__snapshots__/download-table.test.tsx.snap
Allows the table to scroll when the viewport's width is smaller than the table's width.
Before:
After:
Fixes #1029
> Allow the Download page's table to scroll horizontally on small width viewports

- src/components/InstallTabs/index.tsx
Firefox is detected as `UserOS.UNIX` by the detectOS module. (The `navigator.appVersion` output is `5.0 (X11)` ). Given that most users calssified under `UserOS.UNIX` will be using Firefox for Linux and the Linux commands generally run on other UNIX like systems (per https://techahboy.com/2020/08/02/how-to-install-nodejs-via-nvm-under-freebsd-12/), allow users whose OS is classified as UNIX to see the Linux commands.
Bug: #1007
> fix: Render installTabs properly for firefox on linux

- src/components/InstallTabs/InstallTabs.scss
- src/components/ShellBox/ShellBox.scss
Moves all the styling for the shell box to `Shellbox.scss` in an attempt to fix overriding styles. As discussed in https://github.com/nodejs/nodejs.dev/issues/1034 I was unable to test this locally so please do before merging.
Resolves https://github.com/nodejs/nodejs.dev/issues/1034
> style(ShellBox): Remove duplicate ShellBox styles

- src/documentation/0042-node-file-paths/index.md
Just noticed missing quotes in the docs and wanted to contribute :)
> Add missing quotes to a file path in '0042-node-file-paths/index.md'

- .github/workflows/upload-to-staging.yml
GoogleCloudPlatform/github-actions/setup-gcloud is deprecated
Use google-github-actions/setup-gcloud instead
Refs: https://github.com/google-github-actions/setup-gcloud/tree/master/setup-gcloud
> tools: update setup-gcloud github action

- src/components/DownloadAdditional/DownloadAdditional.scss
This PR updates styles for DownloadButton component in order to fix `/download` page Additional Download block
Before:
After:
Fixes #1089
> fix(DownloadButton): Align DownloadButton styles with design

- src/documentation/0021-npm-know-version-installed/index.md
Correct [`npm list`](https://docs.npmjs.com/cli/v6/commands/npm-ls) definition.
> Fix semantic mistake in npm list article

- README.md
- src/documentation/0003-node-installation/index.md
- src/pages/docs.tsx
They moved the repository to the organization in [v0.35.0](https://github.com/nvm-sh/nvm/releases/tag/v0.35.0).
> docs: Update links of nvm and correct its case of name

- src/documentation/0056-node-with-typescript/index.md
When pointing out helpful resources for building applications with TypeScript, I think it would be nice to also point people to [Prisma](https://www.prisma.io/) as an ORM. Prisma provides full type-safety for all DB queries (as opposed to TypeORM where [lots of type guarantees are missing](https://www.prisma.io/docs/concepts/more/comparisons/prisma-and-typeorm#type-safety)).
> docs: add link to Prisma ORM

- .storybook/preview.js
This PR overrides the `__BASE_PATH__` property on `global` to make it readily available to storybook in production build.
Fixes #1092 
1. Checkout branch  - `git checkout fix-storybook-build-error`
2. Run command `npm run build-storybook`. This will generate a static storybook in prod env.
3. Navigate to `public/storybook` and open up `index.html` in a browser. All stories should be running fine.
> fix: override the BASE_PATH in storybook config

- src/documentation/0016-npm/index.md
The package.json example of npm tutorial contains a ',' character in a place that we don't expect it. This breaks `npm run` as it complains that `package.json` is not in an actual json format.
```
$ npm --version
7.6.0
```
```
npm run start
npm ERR! code EJSONPARSE
npm ERR! path /Path/package.json
npm ERR! JSON.parse Unexpected token "}" (0x7D) in JSON at position 81 while parsing near "... \"node app.js\"\n  },\n}\n\n"
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
```
> Fix npm tutorial scripts to use valid JSON example

- src/documentation/0045-node-folders/index.md
The "Read the content of a directory" section contains an example with an import that's not being used (the `path` constant). This PR removes the unused `require()` call.
> docs: Remove unused import from the read directory content example

- src/documentation/0056-node-with-typescript/index.md
docs: Change 'like like that' to 'look like' in 'Node.js with Typescript' documentation. Add a comma after the, "Assuming that our file is named `example.ts`"
> docs: Change 'like like that' to 'look like' in 'Node.js with Typescript' and add a comma

- src/components/InstallTabs/InstallTabs.scss
- src/components/ShellBox/ShellBox.scss
- src/styles/index.scss
- src/styles/install-tabs.scss
- src/styles/tokens.scss
Changed background colors of the terminal window on homepage to the `Pa11y` recommended colors to increase contrast on: 
- selected tab 
- tabs that are not selected 
Note: text colors are unchanged
Fixes https://github.com/nodejs/nodejs.dev/issues/1108
> fix: Color contrast a11y issues on homepage

- src/documentation/0056-node-with-typescript/index.md
The `category` field in the front matter was missed in one of the documentation files in #1282. This PR fixes that.
> Added missing category field

- src/components/Footer/footer.scss
Center footer on desktop view. It looks better centered on desktop imo. See below for change. I accidentally mislabeled my branch and commit, my bad.
changes to this
> style: Centering footer on desktop

- src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
- src/components/Header/index.tsx
* Hide the download header button on mobile view.
* Change width considered mobile from `870` -> `768` to better align with industry standard 
Closes #1322 
Mobile view:
> style: Hide download button from header in mobile view

- src/components/InstallTabs/WindowsPanel/index.tsx
- src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
- test/pages/__snapshots__/home.test.tsx.snap
Updated windows install tab with `nvs` guideline.
In NodeJs docs, we have updated the `nvs` installation steps. `nvs` could be used to install NodeJs in Windows, macOS, and Unix-Like systems. https://github.com/nodejs/nodejs.org/pull/3874
Since we are recommending package manager for macOS and Unix-like systems, updating the Windows installation Tab with `nvs`
Evidence:
https://github.com/nodejs/nodejs.org/issues/3873
> docs: update nodejs installation on windows to `nvs`

- src/documentation/0051-node-buffers/index.md
- Remove wildly misleading text about how Buffers in Node.js are
related to the concept of buffering (they are not!)
- Talk about UTF-8 instead of Unicode when UTF-8 is what the text
is referring to and mention that it is dangerous to act as if
bytes in a Buffer and characters are in 1:1 correspondence (they are not!)
- Recommend using standardized JS methods instead of
Node.js-specific ones where possible
Refs: https://github.com/nodejs/nodejs.dev/pull/1387#pullrequestreview-676905551
> docs: rework Buffer page

- src/components/AboutPageSideNavBar/index.tsx
- src/components/NavigationItem/index.tsx
- src/pages/trademark.tsx
- src/styles/about.scss
- src/styles/layout.scss
- src/types/index.ts
- stories/NavigationItem.stories.tsx
- test/components/__snapshots__/aboutPageSideNavBar.test.tsx.snap
- test/components/aboutPageSideNavBar.test.tsx
- test/pages/__snapshots__/trademark.test.tsx.snap
Added a SideBar for About page
https://staging.nodejs.dev/1399/trademark/
#1354 
The below image is replaced with the latest screenshot after making the changes of wr.
> Add SideBar for `About` Pages

- src/components/AboutPageSideNavBar/index.tsx
- src/styles/about.scss
- src/styles/learn.scss
- test/components/aboutPageSideNavBar.test.tsx
This MR handles width issues caused in mobile devices. Previously the SideBar in mobile view was half in size. this MR will correct it.
| Dark Mode  | Light Mode|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/26359740/122636934-78692680-d109-11eb-8ce5-69421e7d67d7.png) |  ![image](https://user-images.githubusercontent.com/26359740/122636920-6d15fb00-d109-11eb-8c71-bcf8b3314416.png)
#1446
https://staging.nodejs.dev/1448/privacy
> fix: side nav full width in mobile view.

- src/styles/about.scss
- src/styles/learn.scss
The side bar on the about page wasnt floating before. The scss file set `position: inherit;`, but I guess you cant inherit the sticky property. Also removed the `top` because when you scrolled to the bottom of the page it would cut off part of the navbar.
https://github.com/nodejs/nodejs.dev/issues/1474
> style: setting side nav to float

- src/documentation/0035-javascript-async-await/index.md
Fix a problematic term used in the documentation page `modern-asynchronous-javascript-with-async-and-await`.
The Holocaust was a long time ago, but reading that term still makes people twitch.
Rephrase it as "the ultimate solution" to avoid that issue; it's arguably a more apt phrasing anyway.
> docs: Rephrase "final solution" as "ultimate solution"

- src/documentation/0006-v8/index.md
Fix broken link in the index page of 'getting started' section
This page has the JavaScript that each browser use: https://nodejs.dev/learn/the-v8-javascript-engine. However, the link to the Firefox JS engine (SpiderMonkey) is broken.
This PR fixes the broken link.
> fix broken link

- src/components/InstallTabs/LinuxPanel/index.tsx
- src/components/InstallTabs/MacOSPanel/index.tsx
- src/components/InstallTabs/WindowsPanel/index.tsx
- src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
- src/components/InstallTabs/__tests__/__snapshots__/linux-panel.test.tsx.snap
- src/components/InstallTabs/__tests__/__snapshots__/macos-panel.test.tsx.snap
- test/pages/__snapshots__/home.test.tsx.snap
`/download/package-manager` was opening in a new window but shouldn't because it's part of the same domain now
> fix: 🐛 internal links shouldn't open a new window

- CONTRIBUTING.md
- README.md
The remark-lint-preset was disabled because of the false positves, but it did catch a few real issues
> fix: links in supporting MDs

- content/about/working-groups.md
- src/pages/working-groups.tsx
- test/pages/__snapshots__/working-groups.test.tsx.snap
I noticed the `working-groups` page wasnt using a TOC and instead had a bulleted list below the title. This PR implements the TOC and removed the bulleted list.
#1663
> fix: Adding toc for working-groups page

- src/documentation/0013-node-output-to-cli/index.md
Signed-off-by: Rommy Gustiawan <rgcppp@gmail.com>
Fixing syntax error (possibly typo) in documentation file, from `counterReset()` to `countReset()`.
`counterReset()` is not a valid method in JavaScript.
> docs: Fix typo counterReset to countReset

- src/documentation/0020-package-lock-json/index.md
clarification to docs
clarification to docs, as 'npm install' doesn't use 'exactly' the packages defined in package-lock.json, it will update package-lock.json based on semver of packages.json as I understand.  'npm ci' will do what the text describes
> docs: update reference to npm install

- .github/workflows/generate-preview.yml
- .github/workflows/upload-to-staging.yml
`actions/github-script@v5` recently got a breaking change where `github.issues...` in script section had to be replaced by `github.rest.issues...`, and that's causing the preview generation to fail.
https://github.com/actions/github-script#breaking-changes-in-v5
> Fix preview link generation workflows

- src/documentation/0057-node-with-web-assembly/index.md
This merely fixes the spelling of `its`, which is already the possessive form.
> docs: fix typo in WebAssembly doc

- src/documentation/0047-node-module-path/index.md
Resolves `path.format` to print `'/Users/joe/test.txt'` instead of `'/Users/joe/testtxt'` by using `.txt` as ext in function.
N/A
> docs: adjust ext argument in format example for 0047-node-module-path

- package-lock.json
- package.json
This PR bumps `remark-preset-lint-node` to v3.3.0
For some reason - `unified-lint-rule` was locked to older version and because of this - [CI failed](https://github.com/nodejs/nodejs.dev/runs/4081229486?check_suite_focus=true#step:5:23) in PR from Dependabot
Fresh version of `unified-lint-rule` added to `package.json`
Related to #1937
> chore: bump remark-preset-lint-node@3.3.0

- .github/dependabot.yml
Currently not all dependency PRs are shown because it hits the 10 PR limit
> chore: Increase Dependabot PR limit

- src/documentation/0044-node-writing-files/index.md
According to [the Node.js docs](https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options), `fs.writeFileSync` returns undefined. So, I think there's no point to assign the return value to the `data` variable in the example and this could possibly mislead readers.
> no need to assign what fs.writeFileSync returns to a variable

- .github/workflows/cleanup-staging.yml
- .github/workflows/generate-preview.yml
This PR restricts permissions on the `pull_request_target` workflows to the minimum required.
I've tested the changes in a private repo, but had to stub out the GCloud and Build steps. As far as I can tell those don't need any extra permissions.
> tools: Restrict workflow permissions

- cloudbuild-deploy.yaml
16 is now LTS, and 12 is using an older NPM that doesn't support packagelock v2
> chore: use Node 16 for Cloud Build

- .github/workflows/gatsby.yml
- .github/workflows/test.yml
- .storybook/main.js
- package-lock.json
- package.json
- Added missing @babel plugins causing initial build issue
- Downgrade node-sass since it is incompatible with current CRA
- Removed unreferenced storybook plug-in that is subdependency already
- Add Storybook build to CI to prevent future regressions
> fix: Storybook build

- svgo.config.js
**Add a svgo config (svgo.config.js) that disables the removal of the `viewBox` attributes on SVGs. The absence of the `viewBox` attribute prevents the SVGs from scaling correctly.**
In the download page, this caused the Mac Installer icon to be "cropped" and prevented the selected download option icon to grow in size (48px to 56px).
Svgo is used by svgr (@svgr/webpack & gatsby-plugin-svgr).
Fixes #2143 
The contribution guide says that "Pull Requests for a new feature or bug fix must include tests" but I don't know how to test it. It's mocked (svgMock.tsx) for the tests.
> fix: Add svgo config to fix svgs scaling issue

- cloudbuild-deploy.yaml
Default timeout is 10 minutes and our build now is longer than that.
Fixes https://github.com/nodejs/nodejs.dev/issues/2145
> build: extend timeout to 15 minutes

- src/documentation/0052-nodejs-streams/index.md
Use consistent naming convention.
> docs: use lower camel case for variable names.

- src/components/ShellBox/ShellBox.scss
This PR changes the background colour of the shell box buttons from `--brand2` to `--brand7`. This increases the contrast to 6.51, which meets the WCAG AA standards for text contrast.
As far as I know, there are no issues related to this.
> fix: increase button contrast

- package-lock.json
bump follow-redirects from 1.14.5 to 1.14.7
> chore: bump follow-redirects from 1.14.5 to 1.14.7

- .github/dependabot.yml
The Gatsby and Storybook dependencies are pretty noisy in their release patterns.  And we don't always get to the current bumps every week. This reduces the frequency of the dependecy updates to once a month, that should be a little more workable
> chore: move Dependabot to monthly updates

- src/documentation/0013-node-output-to-cli/index.md
Fixes a typo in the page 'Output to the command line using Node.js'
URL => https://nodejs.dev/learn/output-to-the-command-line-using-nodejs
This PR replaces 'years' with 'ears' shown in the image below
#2258
> Fix typo in documentation

- src/documentation/0013-node-output-to-cli/index.md
To use `const chalk = require("chalk");` you have to install version 4 of the `chalk` package. Their newest version is pure ESM and will give an error: `(node:61082) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`. You could update the documentation to explain how to use ESM, but I don't think this is the right place for that, so I think this is the right change.
> Docs: Change chalk version in a code example, as v5 is now Pure ESM

- src/documentation/0001-node-introduction/index.md
In the [Introduction to Node.js](https://nodejs.dev/learn#nodejs-frameworks-and-tools) under the Node.js Frameworks and Tools section, clicking on the Egg.js which is the second one redirects to the link https://eggjs.org/en/ from which we cannot come back using the history stack and it gives the warning Sorry that page is missing which then redirects to https://eggjs.org/.
Fixes #2320
> Fix: incorrect link in Introduction to Node.js

- src/documentation/0016-npm/index.md
pnpm had changed the domain from **pnpm.js.org** to **pnpm.io**. pnpm is mentioned in the lesson [An introduction to the npm package manager](https://nodejs.dev/learn/an-introduction-to-the-npm-package-manager#introduction-to-npm) while saying the alternative npm cli. 
pnpm domain change **[commit](https://github.com/pnpm/pnpm.github.io/commit/aa63e77d46badc6e95f7afa68e6e44a572aa10d4)**.
> Fix: pnpm domain change in Introduction to the npm package manager

- src/documentation/0007-node-run-cli/index.md
Changes the "bash" code header for "app.js" at the getting started lesson [run node from the command line](https://nodejs.dev/learn/run-nodejs-scripts-from-the-command-line).
> docs: change bash to app.js at getting started tutorial

- src/documentation/0039a-node-request-data/index.md
Change `body-parser` reference to `express.json()` 
This middleware is available in Express v4.16.0 onwards,  and also is the one you are using in the example.
> update docs: changes body-parser to express.json() middleware

- src/documentation/0004-node-javascript-language/index.md
The 'closure' wasn't hyperlinked to any resource, hence hyperlinked it to the mdn docs
> Added missing llink for 'closure'

- package-lock.json
- package.json
- Bumps jest to v28
- Adds jsdom environment as separate package
- Enables GH comments for failed Jest tests in PRs
#2398
> chore(tests): Bump jest v28, enable GH Actions reporter

- src/documentation/0031-node-setimmediate/index.md
The docs shows how to use `promise` `nextTick` `immediate` to add callbacks in the queue, but the execution order of them is always confusing for beginners. So I add an example and explanation to show the execution order of them.
[About Promise & process.nextTick](https://github.com/nodejs/help/issues/1789)
#2071
> Docs example of order between promise nextTick immediate.

- src/documentation/0023-update-npm-dependencies/index.md
The final command was `npm update` but should be `npm install`. Improved readability in some places.
> docs: correct wrong command on final step for ncu

- src/components/DownloadAdditional/DownloadAdditional.scss
This PR fixes the `padding` and `border-radius` for the Additional Downloads section. It tries to follow the Figma's without breaking other aspects.
> fix(download): fixed border-radius and padding based on figmas

- src/pages/about.tsx
- src/pages/community.tsx
- src/pages/docs.tsx
- src/pages/download/package-manager.tsx
- src/pages/governance.tsx
- src/pages/privacy.tsx
- src/pages/releases.tsx
- src/pages/resources.tsx
- src/pages/security.tsx
- src/pages/trademark.tsx
- src/pages/working-groups.tsx
- src/templates/blog.tsx
- src/templates/learn.tsx
- test/pages/__snapshots__/about.test.tsx.snap
- test/pages/__snapshots__/community.test.tsx.snap
- test/pages/__snapshots__/governance.test.tsx.snap
- test/pages/__snapshots__/privacy.test.tsx.snap
- test/pages/__snapshots__/releases.test.tsx.snap
- test/pages/__snapshots__/resources.test.tsx.snap
- test/pages/__snapshots__/security.test.tsx.snap
- test/pages/__snapshots__/trademark.test.tsx.snap
- test/pages/__snapshots__/working-groups.test.tsx.snap
- test/pages/download/__snapshots__/package-manager.test.tsx.snap
- test/templates/__snapshots__/blog.test.tsx.snap
- test/templates/__snapshots__/learn.test.tsx.snap
Going through the code I found that Footer component is added manually along with fragment in so many layouts. Although layout itself has a footer inside of it 
- https://github.com/nodejs/nodejs.dev/blob/0b3901550fdece75d7d573f6776b66788d0261de/src/components/Layout/index.tsx#L40
It is better that we have it only in layout and not in all components separately. I checked with all pages and changes are working fine 👍🏻 in UI
> chore: remove footer component and consume it from layout

- src/pages/download/index.tsx
- test/pages/download/__snapshots__/index.test.tsx.snap
<!--## Description
Added a redirect link to "/download/package-manager" page from the "/download" page in the header description.
This PR fixes #2567
> Added Link to package-manager page from the downloads page release-description

- src/documentation/0056-node-control-flow/index.md
Chapter on control flow was added.
Addresses #608
> docs: Add chapter on control flow (#608)

- .github/ISSUE_TEMPLATE/docs.yml
This commit fixes the `validations` field on the wrong indentation level. Invalidating this config.
> fix(issue-templates): docs template padding

- src/templates/blog.tsx
The recent posts on blog has some visual issue which kind of looks like the list is not stable and is changing whenever we visit a different post. We have removed the filtration added to the recent posts list which removed the current active post from the recent section causing the visual error.
Fixes #2570
> refactor(blogs): revert active post filtration for recent posts list

- firebase.json
- gatsby-config.js
- package-lock.json
- package.json
This PR introduces support to Workbox v6, and fixes Firebase hosting caching the `sw.js` when it should not. By using the latest version of Workbox it introduces several improvements for caching, performance and routing.
> firebase(caching): do not cache the service worker in any hypothesis

- src/i18n/config.json
The `hrefLang` code for "Simplified Chinese" should be `zh-Hans`, while `zh-Hant` for "Traditional Chinese".
> The `t` in `zh-Hant` means "traditional" while `s` in `zh-Hans` means "Simplified".
See references under "Script codes" section on https://hreflang.org/list-of-hreflang-codes/ for "Han (Simplified variant)" and Han (Traditional variant).
This PR tries to fix a mistake in PR #2644
> fix(i18n/config): fix hrefLang for zh-cn & zh-tw

- content/learn/node-run-cli.en.md
To make string argument work with `node` CLI, "-e" or "--eval" option should be added, or it will throw error "MODULE_NOT_FOUND".
> fix: missing option "-e"

- .github/PULL_REQUEST_TEMPLATE.md
Having checklist on the top of the description makes quite hard to catch visually what was PR created for.
> Proposing to push Checklist down in PR description

- .github/workflows/github-pages.yml
This adds a GitHub action to deploy to GitHub Pages.
Once this is landed deployments should start working, but we need to update the settings to deploy from actions rather than to a branch.
We should immediately be able to start playing with the GitHub pages deployed site and if we are happy with the performance / availability we can update the DNS to point at GitHub pages.
> tools: deploy site via GitHub pages

- package-lock.json
- package.json
Running `npm test` locally, ESLint is giving an error for the import without an explicit dependency
```
Z:\nodejs.dev\src\components\Seo\index.tsx
3:1  error  '@gatsbyjs/reach-router' should be listed in the project's dependencies. Run 'npm i -S @gatsbyjs/reach-router' to add it  import/no-extraneous-dependencies
Z:\nodejs.dev\src\hooks\useNavigateToDifferentLocale.ts
2:1  error  '@gatsbyjs/reach-router' should be listed in the project's dependencies. Run 'npm i -S @gatsbyjs/reach-router' to add it  import/no-extraneous-dependencies
✖ 2 problems (2 errors, 0 warnings)
```
> chore: explicit dependency gatsbyjs/reach-router

- package-lock.json
- package.json
Pa11y can be a useful tool, but doesn't look like it's wired into the CI and is likely being covered partially by `eslint-plugin-jsx-a11y`
> chore: remove Pa11y

- README.md
This PR simply removes the orphan "Community Commitee" mention.
> chore(commcomm): removed commcomm mention

- src/components/SideNavBar/__tests__/index.test.tsx
I added more unit tests for SideNavBar component.
* Add tests for rest of the items
* Add tests for rendering https link and closing a link after clicking it
Related to #2744
> Test: Add more tests for SideNavBar component

- package-lock.json
- package.json
- src/__fixtures__/hooks.tsx
- src/components/Codebox/index.module.scss
- src/components/Codebox/index.tsx
- src/components/DataTag/index.module.scss
- src/components/Header/index.tsx
- src/components/RandomContributor/index.tsx
- src/components/SearchBar/index.module.scss
- src/components/SearchBar/index.tsx
- src/hooks/index.tsx
- src/hooks/useNvmVersion.tsx
- src/hooks/useSearchResults.ts
- src/styles/templates/api.module.scss
- src/types/index.ts
- This PR makes dependency updates so that we don't need to merge that massive dependabot PR 😅 
- This PR also fixes a few API design issues
- This PR allows search results for API searches to go directly to the definition
- Fixes https://github.com/nodejs/nodejs.dev/issues/2842
> chore(dependencies): updated dependencies and removed some overrides

- src/util/__tests__/parseApiDocsVersion.test.ts
Added unit tests for parseApiDocsVersion function in util.
directory :- /src/util/test/
Add total of 3 new unit tests.
Related to #2744 
> test(util): add test for parseApiDocsVersion in util

- src/components/DarkModeToggle/__tests__/__snapshots__/index.test.tsx.snap
- src/components/DarkModeToggle/index.tsx
- src/components/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/components/Layout/__tests__/__snapshots__/index.test.tsx.snap
- src/components/Layout/__tests__/__snapshots__/page.test.tsx.snap
- src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
- src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
- src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
- src/templates/__tests__/__snapshots__/learn.test.tsx.snap
- src/templates/__tests__/__snapshots__/post.test.tsx.snap
Just a small change but now the dark mode toggle reads out the state of the button (pressed when dark mode is activated and not-pressed when lightmode is activated) for better feedback for screen reader users.
> fix: add aria-pressed to dark mode toggle

- src/components/CommonComponents/Dropdown/index.tsx
- src/components/CommonComponents/LanguageSelector/__tests__/__snapshots__/LanguageSelector.test.tsx.snap
- src/components/CommonComponents/LanguageSelector/index.tsx
- src/layouts/__tests__/__snapshots__/index.test.tsx.snap
- src/layouts/__tests__/__snapshots__/page.test.tsx.snap
- src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
- src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
- src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
- src/sections/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/templates/__tests__/__snapshots__/learn.test.tsx.snap
- src/templates/__tests__/__snapshots__/post.test.tsx.snap
The new language selector dropdown had a small bug in that if you tabbed through the selections with the keyboard it would automatically change the language to French as you tabbed away from the dropdown. This is not the expected behaviour.
I added a check to the event to make sure only `space` and `enter` keys could trigger a language change.
I also added an aria-expanded attribute to the button so that screen reader users are made aware that the button has a popup and whether it is open or closed.
> fix: lang selector keyboard accessibility

- src/components/DownloadComponents/DownloadAdditional/__tests__/__snapshots__/index.test.tsx.snap
- src/components/DownloadComponents/DownloadToggle/__tests__/__snapshots__/index.test.tsx.snap
- src/components/DownloadComponents/DownloadToggle/index.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/i18n/locales/fr.json
- src/i18n/locales/zh-cn.json
- src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
The second toggle button on the download page didn't have correct aria-checked or aria-label values due to a copy-paste mistake I am guessing. They are now updated to match the corresponding button. 
While I was there I added them to the translation files ready to be translated.
> Fix: download toggle button accessibility/translation support

- src/components/CommonComponents/SearchBar/index.tsx
1. Check if the search bar closes while moving with the tab key.
2. If there is a search list, go through the list below and move to the theme toggle button.
https://user-images.githubusercontent.com/49237205/197265264-a1cefafa-b2dd-45b7-aab0-86ae7726e378.mov
#2938 
> fix(SearchBar): SearchBar close while navigating tab key

- content/learn/manipulating-files/node-writing-files.en.md
By "convention" you should avoid html on a markdown file
No related issues
> fix(node-writing-files.en.md): markdown

- content/about/about.en.md
The linked page about event loop seems to have been deleted by #2796 , so the link is broken.
> fix: remove link to deleted event loop page

- .github/workflows/firebase-deployment.yml
- .github/workflows/generate-preview.yml
- .github/workflows/github-pages.yml
- .github/workflows/pull-request.yml
- .github/workflows/sync-api.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
I created an action to cache Gatsby's build outputs. This action is easy to set up. 
**AS-IS**
```yaml
- name: Gatsby Cache Folder
uses: actions/cache@v3
with:
key: cache-folder-ubuntu-latest
path: .cache
- name: Gatsby Public Folder
uses: actions/cache@v3
with:
key: public-folder-ubuntu-latest
path: public
```
**TO-BE**
```yaml
- uses: jongwooo/gatsby-cache@v1.1.0
with:
key: build-gatsby-ubuntu-latest
```
- [https://github.com/jongwooo/gatsby-cache](https://github.com/jongwooo/gatsby-cache)
N/A
> ci: Use gatsby-cache action to cache gatsby build outputs

- content/api/v16/buffer.en.md
- content/api/v16/documentation.en.md
- content/api/v16/process.en.md
- content/api/v16/util.en.md
- content/api/v18/async_hooks.en.md
- content/api/v18/buffer.en.md
- content/api/v18/documentation.en.md
- content/api/v18/process.en.md
- content/api/v18/util.en.md
- content/api/v19/async_hooks.en.md
- content/api/v19/buffer.en.md
- content/api/v19/documentation.en.md
- content/api/v19/process.en.md
- content/api/v19/util.en.md
- util-node/apiDocsTransformUtils.js
Remove redundant character ">" in documentation md of API v16, v18, v19.
Fixes #3164
> fix: remove redundant character ">" in documentation md

- src/components/CommonComponents/SearchBar/index.module.scss
- src/components/CommonComponents/SearchBar/index.tsx
Fix for https://github.com/nodejs/nodejs.dev/issues/3208 issue. Now, complete area is highlighted and made clickable.
> Fix for non-clickable area on Search result
