nodejs/nodejs.dev

.firebaserc
.gitignore
cloudbuild-deploy.yaml
cloudbuild.yaml
firebase.json
gatsby-config.js

Trying one more time to kick off a cloud build on PR

Cloud build

---

.github/main.workflow

build: action to add staging link

---

.github/action/result-poster/Dockerfile
.github/action/result-poster/index.js
.github/action/result-poster/package-lock.json
.github/action/result-poster/package.json
.github/main.workflow
cloudbuild.yaml
gatsby-config.js
package.json

trying to see if this can work

Deploy on pr

---

README.md
yarn.lock

Incorrect steps are currently documented for getting the dev server
up and running. This PR updates the readme to reflect the current
state of the project.

docs: Update to accurately depict workflow.

---

.github/action/result-poster/index.js
cloudbuild.yaml
firebase.json

This may not work right away, let's merge when the dns has propogated.

build: Move to official domain.

---

src/components/header.tsx

fix: Change class to className.

---

src/pages/learn.tsx

This PR adds the ability to navigate to prev and next page of the current active page. Issue no - #32

feat: Add prev and next page link.

---

cloudbuild.yaml

build: Multithread rsync.

---

.travis.yml

build: Initial yaml for travis.

---

README.md

I fixed some typos and grammatical errors in the README.md file.

🐛 FIX: Typos & Grammatical Errors

---

src/pages/learn.tsx

feat: Show 404 page if learn content doesn't exist.

---

src/pages/learn.tsx

refactor: Remove slug regex from Learn page.

---

src/documentation/0001-node-introduction/index.md

This PR adds Fastify to the list of frameworks.

Added Fastify

---

gatsby-config.js
package.json
src/components/header.tsx
src/components/layout.tsx
src/components/seo.tsx
src/config.js
src/pages/404.tsx
src/pages/learn.tsx
test/components/__snapshots__/header.test.tsx.snap
test/components/header.test.tsx
yarn.lock

Hey, folks! 🙌
Would love to be involved in the project. First PR here, closed the #67 since I have refactored the app and included a better reusable SEO component.
Looking forward, peace! ✌️
CC: @MylesBorins kindly check this PR instead.

feat: SEO Component & Application Refactor.

---

src/util/createSlug.js
test/util/createSlug.test.js
test/util/onCreateNode.test.js

Addition to #58 now that we have jest up and running. Should cover the basic scenarios but feel free to point out if I've missed any edge cases 🙂

test: Adding tests for slug generation.

---

gatsby-config.js
package.json
src/config.js
yarn.lock

This PR adds the ability to produce a sitemap of all the site pages including the tutorials.
Looking forward, peace! ✌️

feat: Add sitemap.

---

src/pages/learn.tsx

fix: Edit this page on Github link added on every doc page.

---

src/documentation/0001-node-introduction/index.md

Introduce NestJS Framework
https://nestjs.com/
cc/ @kamilmysliwiec

intro: introduce nestjs framework

---

src/config.js

fix: Display set as browser.

---

src/documentation/0039-node-http-post/index.md

Fix typo [https://nodejs.dev/learn/make-an-http-post-request-using-nodejs](https://nodejs.dev/learn/make-an-http-post-request-using-nodejs).

docs: Fix typo "part".

---

src/components/navigation-item.tsx
src/components/navigation.tsx
src/pages/learn.tsx
src/util/isSmallScreen.ts
test/util/isSmallScreen.test.ts

Use hooks instead of classes
ref: #66

refactor: Use hooks api.

---

src/components/layout.css
src/components/mobile.css

I just fixed it at: #113, but for screen has width < 1262px it still exists. I fix it completely with this PR.

style: Remove scroll by x for screen has width < 1262px.

---

src/components/layout.tsx
src/pages/404.tsx
src/pages/learn.tsx

Adds a better 404 page to Fix #101.
Peace! ✌️

feat: Better 404 page.

---

test/components/__snapshots__/edit-link.test.tsx.snap
test/components/edit-link.test.tsx

Adding tests for EditLink component.

test: Add tests for EditLink component.

---

test/components/__snapshots__/hero.test.tsx.snap
test/components/hero.test.tsx

Adding tests for Hero component.

test: Add tests for Hero component.

---

test/components/__snapshots__/pagination.test.tsx.snap
test/components/pagination.test.tsx

Adding tests for Pagination component.

test: Add tests for Pagination component.

---

src/documentation/0034-javascript-promises/index.md

Fixes for grammar, more examples, clarifications

Update promises tutorial

---

README.md

Removes `Contentful` since we are not using it here.

docs: Fix the description.

---

src/documentation/0001-node-introduction/index.md

Introduce Nx
https://nx.dev/
More information:
https://nx.dev/fundamentals/build-full-stack-applications
cc/ @vsavkin

docs: Introduce Nx.

---

src/documentation/0050-node-module-http/index.md
src/util/isSmallScreen.ts

* Correct typo ~~`persistance~~ to `persistence` in node module http doc
* Update constant variant name to split words "SMALL" & "SCREEN" in "isSmallScreen.ts" file.

refactor: Correct types in node module http doc & isSmallScreen.ts file.

---

test/__fixtures__/page.tsx
test/components/__snapshots__/article.test.tsx.snap
test/components/article.test.tsx

Adding tests for Article component.

test: Add tests for Article component.

---

test/components/__snapshots__/seo.test.tsx.snap
test/components/seo.test.tsx

Adding tests for SEO component.

test: Add tests for SEO component.

---

.prettierrc

As per the discussion in today's meeting, this is the new set of rules as discussed based on #90. Looking forward, peace! ✌️

feat: New Prettier rules.

---

src/documentation/0008-node-terminate-program/index.md

I Fixed some typos in this page. Context: I was reading the site and I spotted some typos. Since the project is hosted on Github, I thought I could fix them and send a pull request. If this one is accepted I will keep send pull requests for them.

Fixed some typos

---

src/documentation/0001-node-introduction/index.md

The overview text has some problems. Replace with a concise paragraph.

docs: Replace overview text.

---

src/components/header.tsx
test/components/__snapshots__/header.test.tsx.snap

feat: Add Download link to header.

---

src/documentation/0004-node-javascript-language/index.md

docs: Fix typo

---

src/components/layout.css
src/components/mobile.css

* Remove `px` when unit is `0`
* Correct css variant name from ~~`--stars-big`~~ to `--stars-large`
* Use `margin` box model’s top position; able to omit ~~`margin-top`~~
* Correct spelling from ~~`programatically`~~ to `programmatically`.

style: Update css in layout.css & mobile.css.

---

.gitignore
gatsby-node.js

Following up on the review https://github.com/nodejs/nodejs.dev/pull/157#discussion_r262810809, initialize with `null` instead of `undefined`. That way, the intent to assign a deliberate non-value is more explicit.
Also, add `.history` to the gitignore list.

fix: Initialize with null to assign a deliberate non-value

---

src/documentation/0003-node-installation/index.md
src/documentation/0012-node-cli-args/index.md
src/documentation/0029-node-event-loop/index.md
src/documentation/0041-node-file-stats/index.md
src/documentation/0049-node-module-events/index.md

docs: Change legacy Node to Node.js

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

Adds Issue and PR templates
closes: #183

Issue and PR templates

---

src/pages/404.tsx
test/pages/404.test.tsx
test/pages/__snapshots__/404.test.tsx.snap

- Adding tests for 404 page
- Removing unused `props`

test: Add tests for 404 page

---

src/documentation/0010-node-hosting/index.md

Updated with links to guides for NodeJS deployment on DigitalOcean/Linode/AWS

Updated with Guides

---

.prettierignore
src/components/navigation-item.tsx
src/components/navigation-section.tsx
src/components/navigation.tsx
src/types/index.ts
yarn.lock

- Unify logic to mark navigation items as done
- Lighten the data structure, tracking only the unique slugs of already read sections
- Use a native set (`Set<NavigationSectionItem['slug']>`) for tracking the above
- Rename the data structure semantically
Refs: https://github.com/nodejs/nodejs.dev/pull/187

 refactor: Simplify logic to mark navigation items as done

---

README.md

We're currently split between two repos. One for administration and one as a codebase. This helps direct people at all the points of interest.
Helps address [#147](https://github.com/nodejs/website-redesign/issues/147) in website-redesign.

Point at the administrative repo from the README

---

test/components/__snapshots__/toc.test.tsx.snap
test/components/toc.test.tsx

- Adding tests for TOC component

test: Add tests for TOC component

---

src/documentation/0052-nodejs-streams/index.md

The table of contents section content is being generated twice.

Table of contents duplication

---

src/documentation/0019-package-json/index.md
src/documentation/0032-javascript-timers/index.md
src/documentation/0034-javascript-promises/index.md

Fixes linking of titles to TOC

---

src/components/author.tsx
src/components/authors-list.tsx
test/components/__snapshots__/author.test.tsx.snap
test/components/__snapshots__/authors-list.test.tsx.snap
test/components/author.test.tsx
test/components/authors-list.test.tsx

This is a follow-up PR to https://github.com/nodejs/nodejs.dev/pull/215. It addresses outstanding nits.
Ref: https://github.com/nodejs/nodejs.dev/issues/209

fix: Add tests and make markup semantic (outstanding nits from #215)

---

src/documentation/0001-node-introduction/index.md

Removed the extra title hash
#208

fix: Review TOC and fix the structure (#208)

---

src/documentation/0002-node-history/index.md

Reword parts of the doc to improve reading flow and sentence structure.
Relates to #3

Brief History of Nodejs Content Scrub

---

src/documentation/0010-node-hosting/index.md

In the 'Where to host a Node.js app' section, we should consider changing the paragraph
> To very popular solutions are:
Serverless Framework
Standard Library
to 
> Two very popular solutions are:
Serverless Framework
Standard Library

docs: Fix minor typo on the index.md file

---

src/documentation/0001-node-introduction/index.md

The typical user just wants to know that V8 is fast, so Node.js is fast.
Make that point and then move on to the next thing.

docs: Make V8 material concise

---

package.json

Remove unused gatsby-source-contentful.

chore: Remove unused dependency

---

src/documentation/0029-node-event-loop/index.md

Delete unbalanced bracket in setTimeout example

---

src/documentation/0013-node-output-to-cli/index.md
src/documentation/0014-node-input-from-cli/index.md
src/documentation/0016-npm/index.md
src/documentation/0019-package-json/index.md

Every commit has a message explaining it.
Not completrly sure about the change from %O to %o.
Besides that, I have more improvements to implement, should I just make one big pull request, or one pull request per main topic?

couple of minor changes

---

CONTRIBUTING.md
README.md
meetings/2018-02-01.md
meetings/2018-02-15.md
meetings/2018-03-01.md
meetings/2018-03-15.md
meetings/2018-03-29.md
meetings/2018-04-12.md
meetings/2018-04-26.md
meetings/2018-05-10.md
meetings/2018-05-24.md
meetings/2018-05-31.md
meetings/2018-09-13.md
meetings/2018-09-27.md
meetings/2018-1-17.md
meetings/2018-10-13.md
meetings/2018-12-06.md
meetings/2019-02-28.md
meetings/2019-03-14.md
meetings/2019-03-28.md
meetings/2019-04-25.md
style-guide/0001-voice-and-tone.md

Merges content from @nodejs/website-redesign per https://github.com/nodejs/website-redesign/issues/147

chore: Merge content from nodejs/website-redesign

---

src/documentation/0047-node-module-path/index.md

fix extname() function

---

src/documentation/0001-node-introduction/index.md

For the documentation, I added a colon to fit with the style of the rest of the document.

Added a colon for consistency and readability

---

package.json
yarn.lock

This eliminates npm audit complaints about commitlint dependencies.

chore: Update commitlint/cli from 7.3.2 to 8.1.0

---

.github/action/result-poster/package-lock.json

This will quell alerts from the GitHub interface and from `npm audit`.

chore: Update dependencies for GitHub action

---

.github/action/result-poster/package-lock.json
.github/action/result-poster/package.json
gatsby-config.js
yarn.lock

Update eslint-utils in two .lock files. Currently-used version is
susceptible to a security vulnerability.

chore: Update eslint-utils

---

README.md

Add Figma Board to Website

---

src/hooks/index.tsx

Adds a hooks directory for custom react hooks
Adds a custom hook for fetching release data from https://nodejs.org/dist/index.json
Meant to address requesting data for #259

Hook use release data

---

src/hooks/index.tsx
src/hooks/useApiDocs.tsx
src/hooks/useReleaseHistory.tsx
src/pages/docs.tsx

- Add API Docs hook.
- Clean up /hooks folder.
- Add of concept API docs page with modules list printed.

API Docs Hook

---

src/components/release-table.tsx
src/pages/download.tsx

Adds release history table to downloads page, modeled off the older mockup [here](https://projects.invisionapp.com/share/KFNHXTOC4J6#/screens/281371444)
Fetches data using `useReleaseHistory` hook, displays first 25 releases.
Related to #259

Release history table

---

src/documentation/0001-node-introduction/index.md

- Improve grammar for **Node.js Frameworks and Tools** section of the page. 
- Replaced all `commas` by `colon`.
- Added links for all the libs in the `Meteor` point since a link for `Vue` was present.
NA

📖Improve Grammar

---

src/documentation/0002-node-history/index.md

This PR edits the [A brief history of Node.js](https://nodejs.dev/a-brief-history-of-nodejs) page to improve the clarity and readability of the points on the page (includes adding bullets for the points).
Also fixes one point that continues at the end of another.

Edit for clarity, readability

---

src/documentation/0005-node-difference-browser/index.md

Fix casing of JavaScript and improve grammar on [Differences between Node.js and the Browser](https://nodejs.dev/differences-between-nodejs-and-the-browser).

Fix casing of JavaScript and improve grammar

---

src/documentation/0006-v8/index.md

Fix grammar on [The V8 JavaScript Engine](https://nodejs.dev/the-v8-javascript-engine)

Fix grammar

---

package.json

I've honestly felt this has introduced more friction then what
it helps us accomplish. Not convinced that consistent commit
messages matter a ton on the site, especially since we are
not doing anything with the commit messages e.g. changelog
Fixes: https://github.com/nodejs/nodejs.dev/issues/321

tools: remove husky

---

.remarkrc
package.json
yarn.lock

Adds the shared config from https://github.com/nodejs/remark-preset-lint-node and disables the rules that don't currently pass to keep the PR easier to review

chore: Add node org remark-lint config

---

.remarkrc
meetings/2019-06-06.md

fix: remark-lint no-heading-indent

---

.remarkrc
CODE_OF_CONDUCT.md
ModerationPolicy.md
README.md
meetings/2018-04-26.md
src/documentation/0002-node-history/index.md
src/documentation/0034-javascript-promises/index.md
style-guide/0001-voice-and-tone.md

fix: remark-lint prohibited-strings

---

.remarkrc
meetings/2018-03-29.md

fix: remark-lint no-tabs

---

src/components/controls.tsx
src/components/header.tsx
src/components/layout.tsx
src/util/DarkModeController.js
test/components/__snapshots__/header.test.tsx.snap
test/components/__snapshots__/hero.test.tsx.snap
test/templates/__snapshots__/learn.test.tsx.snap

This is a prototype implementation for Enhanced Dark Mode.
It adds a new `utils/DarkModeController` controller wrapped in a new `components/controls` component.
---
**Staging**
https://storage.googleapis.com/staging.nodejs.dev/d3449b4/index.html — Manually update to match latest `short commit`
**Pending**
- **Enhancement**: Visual cues for toggle behaviour — see #336
- **Enhancement**: Visual cues for toggle state — see #336
- **Enhancement**: Event handling for controller/components — see #336
**Future**
- Testing: Feature: Enhance Dark Mode to add `auto` and onload restore #336 #354
---
Partially addresses #336

feat: Enhanced Dark Mode prototype

---

src/documentation/0045-node-folders/index.md

Append `()` to the function name

---

src/pages/index.tsx

I'm not a huge fan of the current text:
"The power of JavaScript minus the browser"
This is inaccurate as Node.js is offering a ton of interfaces and
support e.g. system IO that the Browser doesn't offer. Also, while it
is not a browser I do like to think of Node.js as an active participate
in the Web Platform... the comparison here has a negative charge that I
don't think does us any benefit.
I'm offering an alternative title of "JavaScript++", which I think has
a better framing... not a comparison and talking about what we do that
is more. That being said I don't think it is a great title, so perhaps
we should discuss alternatives.

doc: alternative title for landing page

---

src/documentation/0002-node-history/index.md

Update timeline in intro, some grammatical fixes

fix: grammar, update times and references

---

src/documentation/0010-node-hosting/index.md

The current link to creating a Node.js app on Azure points to an incorrect document that's specific to Microsoft Teams. This change corrects the link by pointing to the document for hosting a Node.js application on Azure.

docs: correct azure documentation link

---

src/documentation/0007-node-run-cli/index.md

Add a note (condition) for running the `node.js` command.
NA

Add a note

---

.remarkrc
CONTRIBUTING.md
README.md
meetings/2018-02-15.md
meetings/2018-03-01.md
meetings/2018-03-15.md
meetings/2018-03-29.md
meetings/2018-04-12.md
meetings/2018-05-10.md
meetings/2018-05-24.md
meetings/2018-05-31.md
meetings/2018-09-13.md
meetings/2018-09-27.md
meetings/2018-1-17.md
meetings/2018-10-13.md
meetings/2018-12-06.md
meetings/2019-02-28.md
meetings/2019-03-14.md
meetings/2019-03-28.md
meetings/2019-04-25.md
src/documentation/0011-node-repl/index.md
src/documentation/0016-npm/index.md
src/documentation/0028-npx/index.md
src/documentation/0055-node-inspect-object/index.md
src/documentation/README.md
style-guide/0001-voice-and-tone.md

Enable a few of the remaining disabled remark-lint rules

fix: remark-lint minor suppressed rules

---

src/documentation/0001-node-introduction/index.md

Add MEAN and Loopback to popular frameworks using Node.js
[MEAN.io repo](https://github.com/linnovate/mean)
[LoopBack repo](https://github.com/strongloop/loopback)
they are very popular on github

doc: add MEAN and Loopback 

---

meetings/2020-01-30.md

Thank you for taking notes, @jonchurch and @SMotaal 👍🏽
Notes for #390. 
Closes #390.

Notes for meeting on 2020-01-30

---

src/documentation/0028-npx/index.md

Updated the examples to use a more recent version of Node.js

Update npx examples

---

CONTRIBUTING.md

Added a getting started section on how to contribute.
https://github.com/nodejs/nodejs.dev/issues/396
**Rendered File** — https://github.com/benhalverson/nodejs.dev/blob/docs/CONTRIBUTING.md

docs(contributing.md): Added details on how to contribute

---

src/components/banner.tsx
src/pages/index.tsx
src/styles/tokens.css
test/components/__snapshots__/banner.test.tsx.snap
test/components/banner.test.tsx

A new component to display events in the hero section.
Lightmode and darkmode screenshots included...
**`Feb29`** https://storage.googleapis.com/staging.nodejs.dev/1026c1f/index.html
~~**`Feb29`** https://storage.googleapis.com/staging.nodejs.dev/5c38b45/index.html~~
#332

feat(banner): Added a new banner component

---

src/documentation/0041-node-file-stats/index.md

Fix typo on statSync method

---

OKR.md

This adds an OKR.md doc:
- derives from https://github.com/nodejs/community-committee/blob/3d0329d82fe5d85d8050027c4f4683ab88a01a08/OKR.md
- reflects minutes in https://docs.google.com/document/d/17IuIy9Ir7SHSq7O7UwOsnsoI3vRGL4z1XH-tUeClgMw
- viewable at https://github.com/nodejs/nodejs.dev/blob/add-OKR-doc/OKR.md
Addresses #390

docs: add OKR.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Labels issues automatically
/gcbrun

Auto labels for issue templates

---

src/documentation/0023-update-npm-dependencies/index.md

For the specified package version (`1.3.1`) it would update to `1.13.1`, `1.14.0`... and not `0.13.1`, `0.14.0`

Correct the minor releases versions on line 46

---

src/documentation/0001-node-introduction/index.md

fixed a typo in the documentation

---

.github/main.workflow
.github/workflows/main.yml

This PR updates github workflow from HCL to yml
Addresses #319

chore: update github workflow from hcl to yml

---

package-lock.json

chore: bump minimist@1.2.0 to minimist@1.2.5

---

package-lock.json
package.json

chore: Move tslint to devDependency

---

.github/workflows/result-poster-ci.yml

fix: Globbing for result-poster CI

---

.github/workflows/main.yml

build: Use pinned verion of actions/checkout

---

.github/action/result-poster/package-lock.json
.github/action/result-poster/package.json

chore: remove unused nock module in GitHub action

---

src/documentation/0010-node-hosting/index.md

Sorry for creating a whole PR for such a trivial thing.

0010-node-hosting -> removed an excessive 'a' article

---

.github/workflows/gatsby.yml
.github/workflows/test.yml

Notice after this landed that it isn't that clear to users what a failing job is flagging. Should make it clearer whether the changes aren't building the site vs. style/test issues. The testing vs. linting could be further split out, but i'd leave that till later

chore: Split GitHub actions

---

src/documentation/0052-nodejs-streams/index.md

line 20 was "build" should be "built"

---

.github/PULL_REQUEST_TEMPLATE.md

Update template, test that the new pipeline works as expected

doc: add note about preview to PR template

---

OKR.md
meetings/2018-02-01.md
meetings/2018-02-15.md
meetings/2018-03-01.md
meetings/2018-03-15.md
meetings/2018-03-29.md
meetings/2018-04-12.md
meetings/2018-04-26.md
meetings/2018-05-10.md
meetings/2018-05-24.md
meetings/2018-05-31.md
meetings/2018-09-13.md
meetings/2018-09-27.md
meetings/2018-1-17.md
meetings/2018-10-13.md
meetings/2018-12-06.md
meetings/2019-02-28.md
meetings/2019-03-14.md
meetings/2019-03-28.md
meetings/2019-04-25.md
meetings/2019-06-06.md
meetings/2020-01-30.md
package-lock.json
package.json

New rules were added in the latest release, so the Dependabot PR failed. This addresses them and includes the bump.

fix: Bump and address new rules for remark-lint-node-preset

---

src/components/Banner/Banner.scss
src/components/Banner/__tests__/__snapshots__/banner.test.tsx.snap
src/components/Banner/index.tsx

Removed emotion/core from the banner component and replaced it with scss

refactor(banner): Refactor styling to use scss

---

package-lock.json
src/components/Header/Header.scss
src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
src/components/Header/index.tsx
src/pages/index.tsx
src/styles/index.scss

- Removes the lorem text, company logos, and changes the docs and download to these links https://nodejs.org/en/download/ and https://nodejs.org/en/docs/ until the new pages are completed. 
- It also removes the announcement banner from the homepage.
##Related issues
#654

Homepage text removal

---

src/components/NavigationItem/__tests__/__snapshots__/navigation-item.test.tsx.snap
src/components/NavigationItem/__tests__/navigation-item.test.tsx
src/components/NavigationSection/__tests__/__snapshots__/navigation-section.test.tsx.snap
src/components/NavigationSection/__tests__/navigation-section.test.tsx
src/containers/Navigation/__tests__/__snapshots__/navigation.test.tsx.snap
src/containers/Navigation/__tests__/navigation.test.tsx

Description
Sanity test cases for for Navigation, NavigationSection & NavigationItem. Add up to the coverage.
Related Issues
Addresses #409

test: Navigation, NavigationItem, NavigationSection

---

src/templates/learn.tsx

Fix table of contents links
#701

Fix table of contents links

---

package-lock.json
src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
src/components/Header/index.tsx
src/components/Hero/Hero.scss
src/styles/index.scss
src/styles/layout.scss
src/styles/mobile.scss

Improve & fix responsiveness of the landing page
Fixes #699

style: Fix responsiveness for landing page (Fixes #699)

---

src/documentation/0023-update-npm-dependencies/index.md

Example update values did not match the stated version allowances

docs: Fixed error in semver values on line 46

---

src/components/installTabs.tsx
src/styles/index.scss
src/styles/install-tabs.scss
test/components/__snapshots__/installTabs.test.tsx.snap

Improved styling of `installTabs` components
Related #333

Improved styling for installTabs component

---

src/components/Hero/Hero.scss
src/styles/article-reader.scss
src/styles/index.scss
src/styles/layout.scss
src/styles/learn.scss
src/styles/mobile.scss

Fix responsiveness of learn page
- Bring up hamburger menu option
- Fix navigation responsiveness
- Support theme in sidenav hamburger styling
Fixes #707

Learn page responsiveness Fix #707

---

.github/workflows/upload-to-staging.yml

chore: Use "types" to match Actions schema

---

README.md

Fixed Readme Issue #725 
Link to the issue that is fixed by this PR : Fixes #725

Fixed Issue #721

---

src/pages/index.tsx

This should not have landed when staging was merged into master. Please review asap so we can land

chore: Remove companies from landing page

---

CONTRIBUTING.md

Information is duplicated and stale

docs: Fix getting started guide

---

src/documentation/0011-node-repl/index.md

Signed-off-by: Josh Whetton <whetton.josh@gmail.com>
Correct spelling error based on context.
N/A

Fix: Spelling mistake in REPL dot commands

---

src/styles/mobile.scss

Fixes unresponsiveness mentioned in #744 
Fixes #744

bugfix: Fix unresponsiveness (#744)

---

src/documentation/0001-node-introduction/index.md

Thank you so much for mentioning [Nx](https://nx.dev)! As a maintainer of [Nx](https://github.com/nrwl/nx), I'd like to revise the description for Nx on the nodejs.dev site.
EDIT: Final last-minute update:

docs: Revise description for Nx

---

package-lock.json
src/components/InstallTabs/InstallTabs.scss
src/components/InstallTabs/__tests__/__snapshots__/index.js.snap
src/components/InstallTabs/index.tsx

Replaced content in installTabs as suggested in #726.
Updated test snapshot for the component
Positioned button to the right
Addresses #726

Fix installTabs content

---

src/documentation/0033-javascript-callbacks/index.md

A correction to the sentence "allowing the computer **can** execute other things in the meantime".
**can** should be **to**

sentence error

---

src/documentation/0011-node-repl/index.md

Added a Note about What is REPL? to assist a newbie who never used a REPL before.

Added basic info about REPL on nodejs.dev

---

src/documentation/0021-npm-know-version-installed/index.md

Fix typo and minor changes to phrasing.

Fix typo and minor changes to phrasing

---

src/documentation/0011-node-repl/index.md

Update for a recent change made in PR https://github.com/nodejs/nodejs.dev/pull/741/files

Update "Run" to "Read" for REPL definition

---

src/documentation/0011-node-repl/index.md
src/pages/docs.tsx

Refactoring of renderArticleSections, mainly to remove a lot of if else condition
Addresses #752

refactor: Docs Page

---

README.md

This updates the link to the Figma file in the README. h/t @bnb for the link 🎨 🔗 
N/A

Use correct Figma link

---

.storybook/addons.js
.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
stories/Banner.stories.tsx
stories/EditLink.stories.tsx
stories/Footer.stories.tsx
stories/Header.stories.tsx
stories/Hero.stories.tsx
stories/InstallTabs.stories.tsx
stories/NavigationItem.stories.tsx
stories/NavigationSection.stories.tsx
stories/Pagination.stories.tsx
stories/ReleaseCards.stories.tsx
stories/ReleaseTable.stories.tsx
stories/ReleaseToggle.stories.tsx

Picking up where #759 stopped. 
Fixes #756
Storybook setup plus stories for most of the components. 
emotion CSS working properly, though manual importing could be improved.

storybook init setup

---

.github/workflows/upload-to-staging.yml

Correct NPM call to match https://github.com/nodejs/nodejs.dev/blob/15c27b4c76b9712f6fde59d4525df44ce2c9409a/package.json#L68
#845

fix: preview command had build-storybook backwards

---

.github/workflows/cleanup-staging.yml

https://github.com/GoogleCloudPlatform/github-actions/blob/master/setup-gcloud/README.md appears to need checkout@v2 to pass along the credentials
May address #846

fix: Add checkout@v2 for credential passing

---

cloudbuild-deploy.yaml

s/storybook-build/build-storybook

tools: fix deploy script

---

.github/workflows/cleanup-staging.yml

fix: Force cleanup to succeed

---

.github/workflows/generate-preview.yml

* change label to `create-preview`
* update labels throughout progress to give status
* add label if job fails
* fix error with remove label

tools: improve label preview

---

.github/workflows/generate-preview.yml

Trying something a bit different... hard to know what is available in the context.
If this completely fails I'll try experimenting with one of my own repos before opening another PR

tools: fix preview by label

---

.github/workflows/upload-to-staging.yml

Took @mmarchini tip from the label version and applied it here. This means the comments show up as "Skipped" rather than running the initial steps for every comment in the repo

chore: Use top level event filter for preview

---

.github/workflows/generate-preview.yml

Rollback variable swapping, and use plain interpolation

fix: Use interpolation for preview label ID

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json

Fixes broken backlinks from changing the url slug to /learn/
Fixes #757

Fixed backlink issue with createRedirect

---

src/components/InstallTabs/index.tsx

fixes #876 
fixes #875
don't render the tablist if the OS doesn't match

fix mobile view and check for os before rendering

---

src/components/InstallTabs/MacOSPanel/index.tsx

Updated Mac download script

---

README.md

This commit includes everyone from the nodejs-dev team to the README.md 
#796

Update README to include nodejs-dev members

---

src/containers/Navigation/index.tsx

sidebar scroll was testing for 'isOpen' which is related to the mobile navigation, so it always fails. We can test to make sure isOpen only fails when in mobile breakpoint. 
fixes #862

allow sidebar scroll on desktop widths

---

src/documentation/0028-npx/index.md

Small change to enhance the readability of line 46.

improved 0028-npx/index.md wording

---

src/documentation/0002-node-history/index.md

In my last commit I forgot to add myself as an author for updating 2019 and 2020 Node.js releases

Update authors of index.md

---

meetings/2020-08-27.md

We had a good meeting today with multiple folks. Let's get those notes
back into the repo for long term reflection
Copied the meeting notes over and applied some minor markdown related updates. (Feel free to suggest other updates.)
Closes #892

chore(meeting-notes) Update notes for 2020-08-27

---

README.md

Adds an updated folder tree list to readme file.
Fixes #893

README: update folder tree structure

---

CONTRIBUTING.md

Add note to CONTRIBUTING.md on how to use Storybook
Closes #894

docs(contributing.md): add Storybook note

---

docs/adr/0000-adopt-decision-records.md
docs/adr/README.md
docs/adr/template.md

Architecture decision records are a useful tool for documenting the
context surrounding existing and new architecturally significant design
decisions.
This pr just gets us started with an initial document to lay some
groundwork.
Adds basic support for ADR's
Please note! I realize there's some lint errors with regards to the templates, I'll revisit tomorrow...
- Closes #853 (or at least gets us started)

feat(adr): Adopt Decision Records

---

meetings/2020-09-03.md

We came and met and chatted about a couple of issues. These are the notes from that meeting.
- Meeting notes as copied over from the google document.
- Thanks to @designMoreWeb's careful work during the meeting, there wasn't much to reformat in the process! 💪 
- Closes #905

docs: WG Meeting Notes 2020-09-03

---

src/components/DownloadCards/__tests__/__snapshots__/download-cards.test.tsx.snap
src/components/DownloadCards/__tests__/download-cards.test.tsx
src/components/DownloadHeader/__tests__/__snapshots__/download-header.test.tsx.snap
src/components/DownloadHeader/__tests__/download-header.test.tsx
src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
src/components/DownloadReleases/__tests__/download-releases.test.tsx

This PR introduces new tests for multiple components (specified in the pull request title).

test: Create tests for DownloadCards, DownloadHeader and DownloadReleases

---

.github/workflows/test.yml
.remarkrc
package.json

Doesn't fix the existing issues, but adds it back so no future ones are added, and the existing ones can be fixed in separate PRs
Related to #931

chore: Add remark-lint back to CI

---

.remarkrc
CONTRIBUTING.md
OKR.md
README.md
docs/adr/0000-adopt-decision-records.md
docs/adr/README.md
docs/adr/template.md
meetings/2020-08-27.md
meetings/2020-09-03.md
src/documentation/0002-node-history/index.md

Cleanup issues flagged since linting wasn't enforced in CI for awhile
Fixes #931

fix: remark-lint rules from node preset rules

---

src/components/DownloadReleases/__tests__/__snapshots__/download-table.test.tsx.snap
src/components/DownloadReleases/__tests__/download-table.test.tsx

This PR adds new tests to DownloadTable component.
Additionally, I was thinking if introducing sometime more types of tests (RTL component tests, hook tests, e2e tests eventually) to this repository wouldn't be beneficial. While snapshot tests are useful in some circumstances, they're definitely not endgame 😏

test: Create tests for DownloadTable component

---

src/components/DownloadCards/index.tsx
src/components/DownloadHeader/__tests__/__snapshots__/download-header.test.tsx.snap
src/components/DownloadHeader/index.tsx
src/components/DownloadReleases/DownloadTable.tsx
src/components/DownloadReleases/index.tsx

I'm not sure if pull requests like that are welcome, but I saw an opportunity to improve few things while adding tests in my last PR. This pull requests introduces multiple minor adjustments in components related to download for the sake of consistency, conventions and readability. Zero changes in functionality 😄
Besides that, after some browsing through the repository code, I've noticed that there is no single code style convention that is kept. Maybe it would be worth looking into creating guide for code style and adjust repository to it. I'm thinking about stuff like grouping imports, components, naming etc. 🤔

refactor: Introduce few minor improvements in components related to download

---

src/documentation/0012-node-cli-args/index.md

`process.argv` is an array and arrays doesn't have arguments

Content - Fix missleading typo

---

gatsby-config.js
package-lock.json
package.json
src/components/ImageFigure/ImageFigure.scss
src/components/ImageFigure/index.tsx
src/components/Layout/centered.tsx
src/pages/sites/benchmarking.mdx
src/styles/centered-layout.scss

Added a new `ImageFigure` component for images with captions / HTML semantics /
Added a new 'CenteredLayout' for pages that don't align with the `index` layout. /HTML semantics/
- Uses `<main>` instead of `<span>`
- `<main>` is centered using auto left/right margin; displayed flex column
New benchmarking `.mdx` page to address #884
Used `ImageFigure` component to display benchmark images

Issue/884  Benchmarks page

---

src/documentation/0019-package-json/index.md
src/documentation/0028-npx/index.md
src/documentation/0045-node-folders/index.md
src/documentation/0048-node-module-os/index.md

Small typo fixes in the documentation.

Minor Typo Fixes

---

package-lock.json
package.json
src/components/DownloadToggle/__tests__/__snapshots__/download-toggle.test.tsx.snap
src/components/DownloadToggle/__tests__/download-toggle.test.tsx

Some time ago [I suggested introducing new robust tools](https://github.com/nodejs/nodejs.dev/pull/938) for testing and this proposition was welcome. One of the best bets currently is [@testing-library/react](https://testing-library.com/docs/react-testing-library/intro). It enables writing useful tests with ease.
In addition to installing it, I wrote new tests for previously untested component using freshly installed library.

test: Install @testing-library/react and add tests for DownloadToggle

---

src/styles/mobile.scss

Fix sidebar background color when using darkmode

Learn-page: fix sidebar background on darkmode

---

src/components/DownloadReleases/DownloadTable.tsx
src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
src/components/DownloadReleases/__tests__/__snapshots__/download-table.test.tsx.snap
src/components/DownloadReleases/__tests__/download-releases.test.tsx
src/components/DownloadReleases/__tests__/download-table.test.tsx
src/components/DownloadReleases/index.tsx
src/hooks/useReleaseHistory.tsx
src/pages/download.tsx

Changed the release table at `/download` from dynamic to static with data from https://nodejs.org/en/about/releases/
Addresses #949

Docs: Updated Downloads Table to Static Data

---

package-lock.json
src/components/DownloadReleases/DownloadTable.scss
src/components/DownloadReleases/DownloadTable.tsx
src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
src/components/DownloadReleases/__tests__/__snapshots__/download-table.test.tsx.snap
src/styles/layout.scss
src/styles/tokens.scss

Adds styles to the downloads table based on the Figma designs: https://www.figma.com/file/lOxAGGg5KXb6nwie7zXkz6/NJ---Design-System?node-id=0%3A1652
Before:
After:
Related to #840.

Add styles to Downloads table

---

.eslintrc.js
package-lock.json
package.json

Cleaned up repeated entries in .eslintrc.
Installed linter plugin that will help us stick with good testing practices.

chore: Clean up .eslintrc and install eslint plugin for @testing-library/react

---

README.md

In #963, a new `gatsby-browser.js` was added to the top-level files, which was missing in Readme.
Also, I added a line on how to view stories locally for ease.
None

Docs: Update README according to latest changes

---

meetings/2020-10-14.md
meetings/2020-10-21.md

docs(meeting notes): Created meeting notes in markdown format

---

README.md

This is auto generated based on GitHub IAM

chore: update team list with ncu-team sync

---

src/styles/tokens.scss

Speed up font color transition between light/dark modes
Resolves https://github.com/nodejs/nodejs.dev/issues/1081

Fix: Speed up font color transition

---

src/documentation/0051-node-buffers/index.md

Fixed typo of word "sensitive" in buffers documentation.

docs: fixed typo in buffers documentation

---

src/documentation/0003-node-installation/index.md

Docs: Fix grammar in 0003-node-installation

---

src/documentation/0023-update-npm-dependencies/index.md
src/documentation/0032-javascript-timers/index.md

Reworded "To update to a new major version all the packages, install the npm-check-updates package globally:"
Reworded "To update to a new major version all the packages, install the npm-check-updates package globally:".
Changed it to "To update all packages to a new major version, install the `npm-check-updates` package globally:" to make it a little bit more clear.
N/A

Updated text in src/documentation/0023-update-npm-dependencies/index.md and src/documentation/0032-javascript-timers/index.md 

---

src/documentation/0054-node-exceptions/index.md

Corrected function's name called in the chain for clarity between the examples #cosmetics

fixed minor issue in the example

---

src/documentation/0022-npm-install-previous-package-version/index.md

typo: version -> versions

---

src/documentation/0002-node-history/index.md

copy editing change, corrected grammar from singular "has" to plural "have" in the sentence: "It introduces a lot of innovative thinking and approaches for JavaScript server-side development that has already helped many developers."

copy edit: has -> have

---

src/documentation/0018-how-to-use-npm-package/index.md

Minor change for consistent style. For example, `node_modules` is always surrounded with backticks, but missed here.

Minor fix for consistent style

---

src/documentation/0028-npx/index.md

I think "once executed" might be a slightly more correct description of the flow.

Minor change to NPX->index.md ("executed" instead of "downloaded")

---

src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
src/components/Header/index.tsx
src/components/Layout/__tests__/__snapshots__/centered-layout.test.tsx.snap
src/components/Layout/__tests__/__snapshots__/layout.test.tsx.snap
test/pages/__snapshots__/404.test.tsx.snap
test/templates/__snapshots__/learn.test.tsx.snap

This PR changes the download link from nodejs.org/en/download to nodejs.dev/download
It replaces my old PR that was deleted by mistake.  #1020

refactor(Updated link from old download page to new):

---

src/documentation/0008-node-terminate-program/index.md

Add note for express code snippet

---

src/documentation/0016-npm/index.md

[**pnpm**](https://pnpm.js.org/) is also a fairly popular alternative package manager in Node.js ecosystem.
You can view the [comparison between npm, yarn and pnpm](https://blog.logrocket.com/javascript-package-managers-compared/).
This PR lists pnpm as a package manager alternative in addition to yarn.
N/A

docs: List pnpm as an package manager alternative

---

src/documentation/0047-node-module-path/index.md

Add  `path.format()` explanation to the "The Node.js path module" doc

Update 'The Node.js path module' doc

---

src/components/Header/index.tsx

Added the toggle function to the `keyPress` event in Dark Mode Button
Fixes #1147

fix: Dark Mode Button Toggle on Enter Key

---

.github/workflows/test.yml

Run the testing on the default branch pushes so the CodeCov has the base commit for comparison on PRs

chore: Run CI when landing on default branch

---

src/documentation/0037-node-http-server/index.md

I noticed that the example code in the main text was inconsistent with the embedded code from glitch.com, so I made them consistent.

Make example code consistent

---

OKR.md

fix: Fix 'have each have' to 'each have' in OKR.md

fix: Fix 'have each have' to 'each have' in OKR.md

---

content/homepage/index.md
src/pages/index.tsx

Removes the placeholder text from the homepage

fix(homepage): Remove placeholder text from homepage

---

src/components/NavigationItem/__tests__/navigation-item.test.tsx
src/components/NavigationItem/index.tsx
src/pages/community.tsx
src/styles/community.scss
src/types/index.ts

Added sidebar component in `pages/community.tsx` based on figma design [here](https://www.figma.com/file/lOxAGGg5KXb6nwie7zXkz6/NJ---Design-System?node-id=1338%3A12737).
Fixes #1145

feat: Added sidebar component to community page

---

src/documentation/0001-node-introduction/index.md

Grammatical correction.

---

content/community/index.md
package-lock.json
package.json
src/documentation/0056-node-with-typescript/index.md

remark-lint-bump

---

src/components/Article/__tests__/__snapshots__/article.test.tsx.snap
src/components/Article/__tests__/article.test.tsx
src/components/Article/index.tsx
test/__mocks__/throttle-debounce.js

This PR adds more tests for `Article` component related to scroll and history stuff.
Please note - few ts/eslint ignore comments added for partial mock objects creation.
N/A

test(Article): Add more tests for Article component

---

src/documentation/0044-node-writing-files/index.md

I think "The file is created if it does not exist" may read more clearly to international users. Thanks!
I changed some wording in the flags section to read more clearly: "The file is created if not existing" -> "The file is created if it does not exist. " I think this may read more clearly to international users.

clarify file creation in flags section

---

src/documentation/0011-node-repl/index.md

Improve readability by avoiding cap in the middle of a sentence

no caps in the middle of a sentence

---

src/documentation/0054-node-exceptions/index.md

Fixed small typo (IMHO full stop was missed in sentence).

Missed full stop fix

---

src/documentation/0056-node-with-typescript/index.md

Adjusted Typescript installation command (set it to local development install rather than global one)

Edited Typescript installation command

---

package-lock.json
package.json

~~I ran npm audit fix to update the package-lock.json~~
Reverting back to gatsby 3.1.3 to fix the local dev and linting / tests
✅ Closes: #1288

fix: 🐛 local dev webpack issue

---

src/documentation/0001-node-introduction/index.md

Hey! 👋 
Wanted to update AdonisJS name and improve its description.

docs(node): update AdonisJS description

---

src/documentation/0002-node-history/index.md

Add nodeJS v16 to documentation

Add nodeJS v16 to documentation

---

package-lock.json
package.json
src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
src/components/Header/index.tsx

Reverts nodejs/nodejs.dev#1334

Revert "style: Hide download button from header in mobile view"

---

src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
src/components/UpcomingReleases/__tests__/__snapshots__/upcoming-releases.test.tsx.snap
src/components/UpcomingReleases/index.tsx
src/components/UpcomingReleases/upcomingReleases.ts
test/pages/__snapshots__/download.test.tsx.snap

Fixes #1338
Hi @benhalverson, how does this look?
Thanks

Remove Node.js 13 from tabbed view

---

src/components/UpcomingReleases/UpcomingReleases.scss
src/styles/download.scss

Added overflow -x for release tab
Fixes #1369

fixed download overflow

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test.yml
CODE_OF_CONDUCT.md
ModerationPolicy.md
README.md
content/community/index.md
src/components/Article/__tests__/__snapshots__/article.test.tsx.snap
src/components/EditLink/__tests__/__snapshots__/edit-link.test.tsx.snap
src/components/EditLink/index.tsx
src/components/Footer/__tests__/__snapshots__/footer.test.tsx.snap
src/components/Footer/index.tsx
src/components/Layout/__tests__/__snapshots__/centered-layout.test.tsx.snap
src/components/Layout/__tests__/__snapshots__/page-layout.test.tsx.snap
src/pages/sites/metrics.mdx
test/pages/__snapshots__/404.test.tsx.snap
test/pages/__snapshots__/blog.test.tsx.snap
test/pages/__snapshots__/download.test.tsx.snap
test/pages/__snapshots__/home.test.tsx.snap
test/pages/__snapshots__/trademark.test.tsx.snap
test/templates/__snapshots__/blog.test.tsx.snap
test/templates/__snapshots__/learn.test.tsx.snap

Renamed references from master to main for https://github.com/nodejs/nodejs.dev/issues/1163.
The tests will fail till the rename happens though

chore: Rename default branch

---

content/about/resources.md

Address a bug caused in production but worked well in local and staging.
In production, the `resources` page is not loading contents correctly.  Corrected the same by adding `/` prefix to point the resources from the root folder.
#1426

add resources page

---

src/pages/privacy.tsx
src/pages/resources.tsx
src/styles/about.scss
test/pages/__snapshots__/privacy.test.tsx.snap
test/pages/__snapshots__/resources.test.tsx.snap

Added SideNav bar for the newly merged `Resources and `Privacy Policy` pages. 
#1423

Add side navigation bar for resources and privacy pages

---

content/about/about.md
gatsby-node.js
src/components/Footer/__tests__/__snapshots__/footer.test.tsx.snap
src/components/Footer/index.tsx
src/components/Layout/__tests__/__snapshots__/centered-layout.test.tsx.snap
src/components/Layout/__tests__/__snapshots__/page-layout.test.tsx.snap
src/pages/about.tsx
test/pages/__snapshots__/404.test.tsx.snap
test/pages/__snapshots__/about.test.tsx.snap
test/pages/__snapshots__/blog.test.tsx.snap
test/pages/__snapshots__/download.test.tsx.snap
test/pages/__snapshots__/home.test.tsx.snap
test/pages/__snapshots__/privacy.test.tsx.snap
test/pages/__snapshots__/releases.test.tsx.snap
test/pages/__snapshots__/resources.test.tsx.snap
test/pages/__snapshots__/trademark.test.tsx.snap
test/pages/about.test.tsx
test/templates/__snapshots__/learn.test.tsx.snap

About page replacement for https://nodejs.org/en/about/
This might not be needed since we already have a community page that is showing the same info.

feat: 🎸 About page

---

src/pages/community.tsx

Added new sidebar component that replaces older temp one

refactor: 💡 sidebar in community page

---

src/styles/layout.scss

Signed-off-by: Manish Kumar <manishprivet@protonmail.com>
There was an offset issue in desktop screens introduced in a previous PR (#1351) that got missed.
To reproduce it, go to https://nodejs.dev/learn and scroll and observe the header.
None

fix(styles): header Offset

---

README.md

Signed-off-by: Manish Kumar <manishprivet@protonmail.com>
PR to add @manishprivet to the README.md according to the Becoming a Collaborator guideline.
Related to #1343

chore(team): added myself to README

---

src/styles/learn.scss

Fixes close button position in learn page on mobile
Fixes #1453

Fix: Close button position on learn page

---

.github/workflows/cleanup-staging.yml
.github/workflows/generate-preview.yml

tools: update GCP tools for actions

---

.github/workflows/cleanup-staging.yml

the pull_request event doesn't get the secrets

tools: use `pull_request_target` for cleanup action

---

README.md

Have been actively contributing and enjoy working with everyone. Nominated by @benhalverson . Look forward to continuing to contribute!
Addresses #1561

feat: adding lancemccluskey to readme

---

src/components/SideNavBar/index.tsx
test/components/__snapshots__/SideNavBar.test.tsx.snap
test/pages/__snapshots__/about.test.tsx.snap
test/pages/__snapshots__/community.test.tsx.snap
test/pages/__snapshots__/governance.test.tsx.snap
test/pages/__snapshots__/privacy.test.tsx.snap
test/pages/__snapshots__/releases.test.tsx.snap
test/pages/__snapshots__/resources.test.tsx.snap
test/pages/__snapshots__/security.test.tsx.snap
test/pages/__snapshots__/trademark.test.tsx.snap
test/pages/__snapshots__/working-groups.test.tsx.snap
test/pages/download/__snapshots__/package-manager.test.tsx.snap

Sort community pages alphabetically
Updated snapshots

refactor: 💡 sort community pages alphabetically

---

src/documentation/0038-node-make-http-requests/index.md

The domain whatever dot com is a real domain which at the moment of proposing this change is owned by somebody and redirects to some YouTube channel.
It's advisable to use only special designated domains for examples and documentation, such as example.com.

Replace whatever.com with example.com in the documentation

---

package.json
test/util/getBannersData.test.ts
test/util/getNodeReleasesData.test.ts
test/util/getReleaseStatus.test.ts
util-node/getNodeReleasesData.js
util-node/getReleaseStatus.js

https://github.com/nodejs/nodejs.dev/pull/1662#discussion_r677648777

Add missing tests for new until-node files

---

README.md

There were two 'Community' words in the README file, I removed one of them and the links in the readme in the last section were looking clustered, I separated them into different lines.
Fixes #1752

Typo in the README solved

---

src/components/Footer/footer.scss

The styles of the footer were broken, I find out the issue by going through the previous commits and fixed it.
Fixes #1750

fixes: footer styles

---

src/documentation/0018-how-to-use-npm-package/index.md

Grammatical update to index.md

Grammatical update to index.md

---

content/download/package-manager.md

Fixes typo poplar -> popular
N/A

fix: typo poplar -> popular

---

CONTRIBUTING.md
README.md
docs/project-overview.md

This PR does a few things:
* Rewords and condensing some of the language in the README and CONTRIBUTING files. 
* Extracts project information from the readme into a separate `./docs/project-overview.md` file
I want to make it easier for new developers to start contributing. I moved the steps to contribute in CONTRIBUTING.md to the top of the file, extracted project overview information into a separate file, and made a few other small changes.

docs: Condensing getting started docs

---

src/styles/article-reader.scss
src/styles/learn.scss

Added a feature of making mobile navigation bar sticky
Fixes <a href="https://github.com/nodejs/nodejs.dev/issues/1475">#1475</a>

Made side nav bar fixed for mobile view

---

.github/workflows/generate-preview.yml
.github/workflows/upload-to-staging.yml

Related to #1886 
Forgot one last place to make the change 🤦🏼‍♂️

Fix: Preview link generation workflow

---

package-lock.json
package.json
test/hooks/useApiDocs.test.tsx
test/hooks/useNodeJsContributorsApi.test.tsx

chore: Upgrade eslint-plugin-testing-library v5

---

src/documentation/0002-node-history/index.mdx

Updating HAPI url as to its current url (https://hapi.dev/)

fix: Update hapi URL

---

src/documentation/0004-node-javascript-language/index.md

"one fundamental" -->"one of the fundamental parts of the "

Corrected a Typo

---

src/components/InstallTabs/LinuxPanel/index.tsx
src/components/InstallTabs/MacOSPanel/index.tsx
src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
src/components/InstallTabs/__tests__/__snapshots__/linux-panel.test.tsx.snap
src/components/InstallTabs/__tests__/__snapshots__/macos-panel.test.tsx.snap

This change updates the nvm version for both the MacOS tab and Linux tab on the homepage.

docs: ✏️ Update nvm version on MacOS and Linux tabs

---

.eslintrc.js
package-lock.json
package.json
src/components/DownloadCards/DownloadCard/index.tsx
src/components/DownloadCards/index.tsx
src/components/DownloadHeader/index.tsx
src/components/DownloadReleases/index.tsx
src/components/DownloadToggle/index.tsx
src/components/Footer/index.tsx
src/components/InstallTabs/index.tsx
src/components/Layout/page.tsx
src/components/SideNavBar/index.tsx
src/components/UpcomingReleases/UpcomingReleasesItem/index.tsx
src/components/UpcomingReleases/UpcomingReleasesPanel/index.tsx
src/components/UpcomingReleases/index.tsx
src/pages/404.tsx
src/pages/about.tsx
src/pages/community.tsx
src/pages/docs.tsx
src/pages/download/index.tsx
src/pages/download/package-manager.tsx
src/pages/governance.tsx
src/pages/index.tsx
src/pages/privacy.tsx
src/pages/releases.tsx
src/pages/resources.tsx
src/pages/security.tsx
src/pages/trademark.tsx
src/pages/working-groups.tsx

This PR bumps eslint-config-airbnb to v19.
I've disabled [react/function-component-definition](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md) rule for now and I'd like to hear from the Team if we want to enable it with some particular value. In case yes - I'll be more than happy to update code-style.
Related to #2035

chore: Bump eslint-config-airbnb@19

---

src/documentation/0002-node-history/index.mdx

Added Node.js 17 as a release in the list.

Node.js 17 is released

---

src/documentation/0020-package-lock-json/index.md

Updating grammar from "...other programming languages package managers (like Composer in PHP) use a similar system for years." to "...other programming languages package managers (like Composer in PHP) have used a similar system for years."

fix incorrect grammar tense in index.md

---

CONTRIBUTING.md

This PR fixes the internal links in the "Get Started" section so they scroll to the relevant section
Fixes #2117

fix: Update links to match section header IDs

---

src/components/Banner/index.tsx

Fixed invalid URL navigation issue on the banner.
Now the banner component should be supplied with full urn instead of partials.
#2166

Fix incorrect url in banner

---

package-lock.json

bump engine.io from 4.1.1 to 4.1.2

chore: bump engine.io from 4.1.1 to 4.1.2

---

src/documentation/0005-node-difference-browser/index.md

The ESM support is stable since Node.js v12, so we should clarify that in this doc page.
None

docs: Clarify that Node.js supports ESM as well

---

src/components/RecentPosts/RecentPosts.scss
src/components/RecentPosts/__tests__/__snapshots__/recent-posts-test.tsx.snap
src/components/RecentPosts/__tests__/recent-posts-test.tsx
src/components/RecentPosts/index.tsx
src/styles/layout.scss
src/templates/blog.tsx
test/templates/__snapshots__/blog.test.tsx.snap

Implements recent posts list on single blog page
#1151

feat: added recent posts on single blog page

---

.github/workflows/cleanup-staging.yml
.github/workflows/generate-preview.yml

github changed from master to main for setup-gcloud. See
https://github.com/google-github-actions/setup-gcloud/issues/539

chore: 🤖 Fixed failing build for github actions

---

src/documentation/0055-node-with-typescript/index.md

Changes the syntax highlighting from JavaScript to TypeScript.

Change syntax highlighting from JavaScript to TypeScript

---

src/documentation/0029-node-event-loop/index.md

"killer feature" makes more sense in this context IMHO.

feature instead of app

---

src/documentation/0003-node-installation/index.md

'for example' was removed since there were no related examples to it.

Removed text which had no continuation

---

src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
src/components/UpcomingReleases/__tests__/__snapshots__/upcoming-releases.test.tsx.snap
test/pages/download/__snapshots__/index.test.tsx.snap

The snapshot tests were broken. Not sure how it happened...

updated snapshots

---

src/documentation/0039b-node-file-descriptors/index.md
src/documentation/0040-node-file-stats/index.md
src/documentation/0042-node-reading-files/index.md
src/documentation/0043-node-writing-files/index.md
src/documentation/0044-node-folders/index.md
src/documentation/0045-node-module-fs/index.md

Promise-based API is more used in today's development. So I add promise-based examples for all of the fs API tutorials, and at the same time add a simple explanation of callback hell for providing a reason for using promise-based API.
#2234

Docs: Add promise based examples for filesystem.

---

src/components/InstallTabs/LinuxPanel/index.tsx
src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
src/components/InstallTabs/__tests__/__snapshots__/linux-panel.test.tsx.snap

I removed the two duplicate whitespaces in the Linux InstallTabs component.
Fixes #2439

Fix: duplicate whitespace (#2439)

---

src/documentation/0016-npm/index.md

Updated the following lines: 65, 73, 93, 122 
From `console` to `bash` to have syntax highlighting as well as preserving the consistency of the documentation.

Updated index.md

---

src/documentation/0045-node-module-fs/index.md

Changed 'which may causes' to 'which may cause' as it seemed like correct grammar
None

Fix grammatical error

---

src/documentation/0000-socket-programming-with-net-module/index.md

Minor typo fixes
documentaion -> documentation
immediatly -> immediately
succesfully -> successfully
programatic -> programmatic

chore: fix typos

---

.github/workflows/gatsby.yml

Changes typo:
Gastby -> Gatsby
Fixes #2508

fix: Gatsby typo for CI/CD on PR

---

src/documentation/0039a-node-request-data/index.md

I couldn't understand what the statement was trying to say and so I think "got" should be replaced by "gets". I might be wrong though.

grammar fix?

---

src/documentation/0050-node-buffers/index.md

I just noticed a small typo while reading the page while trying to learn node.js

a small typo

---

TRANSLATING.md

This PR introduces Translation Guidelines for Translation contributions.

feat(translation): introduced translation guidelines

---

src/components/Article/__tests__/__snapshots__/article.test.tsx.snap
src/components/Layout/__tests__/__snapshots__/page-layout.test.tsx.snap
src/components/NavigationItem/__tests__/__snapshots__/navigation-item.test.tsx.snap
src/components/NavigationItem/index.tsx
src/components/NavigationSection/__tests__/__snapshots__/navigation-section.test.tsx.snap
src/components/SideNavBar/__tests__/__snapshots__/SideNavBar.test.tsx.snap
src/containers/AuthorList/AuthorList.scss
src/containers/AuthorList/__tests__/__snapshots__/authors-list.test.tsx.snap
src/containers/AuthorList/index.tsx
src/containers/Navigation/__tests__/__snapshots__/navigation.test.tsx.snap
src/pages/__tests__/__snapshots__/community.test.tsx.snap
src/pages/__tests__/community.test.tsx
src/pages/about/__tests__/__snapshots__/governance.test.tsx.snap
src/pages/about/__tests__/__snapshots__/index.test.tsx.snap
src/pages/about/__tests__/__snapshots__/privacy.test.tsx.snap
src/pages/about/__tests__/__snapshots__/releases.test.tsx.snap
src/pages/about/__tests__/__snapshots__/security.test.tsx.snap
src/pages/about/__tests__/__snapshots__/trademark.test.tsx.snap
src/pages/about/__tests__/__snapshots__/working-groups.test.tsx.snap
src/pages/about/__tests__/governance.test.tsx
src/pages/about/__tests__/index.test.tsx
src/pages/about/__tests__/privacy.test.tsx
src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
src/pages/download/__tests__/package-manager.test.tsx
src/pages/resources/__tests__/__snapshots__/index.test.tsx.snap
src/templates/__tests__/__snapshots__/learn.test.tsx.snap

Fixed some accessibility errors for the community page by wrapping the link element in a `li` because a `ul` element expects this.
Also changed the h4 tag to a li for the same reason.

test(community page) a11y community test

---

src/components/Article/index.module.scss
src/components/Header/__tests__/__snapshots__/index.test.tsx.snap
src/components/Header/index.tsx
src/components/Layout/__tests__/__snapshots__/index.test.tsx.snap
src/components/Layout/__tests__/__snapshots__/page.test.tsx.snap
src/components/TableOfContents/index.module.scss
src/components/TableOfContents/index.tsx
src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
src/pages/resources/__tests__/__snapshots__/index.test.tsx.snap
src/templates/__tests__/__snapshots__/blog.test.tsx.snap
src/templates/__tests__/__snapshots__/learn.test.tsx.snap
src/templates/api.tsx
util-node/apiDocsTransformUtils.js

This PR executes several bug fixes and minor improvements:
- Fixes all content from `<article>` components being capitalized
- Increases the Table of Contents font-size
- Adds the Version to top of the Heading of each API Page
- Fixes the "API Docs" section not being highlighted while within an API Doc page
- Fixes removing the "Module: " prefix from the Navigation for Module Pages
- Increases the max-width for an article to 980px
- Fixes calculation of width of the articles to use 100% instead of 100vw
- https://github.com/nodejs/nodejs.dev/issues/2711

fix(design): some small design fixes

---

firebase.json

This PR fixes caching issues caused by Firebase Hosting.

fix(caching): updated correct headers for caching

---

gatsby-browser.tsx
gatsby-config.js
package-lock.json
package.json
src/components/Layout/index.tsx

This PR fixes that CSS is not loaded on the server side. Also adds HTML minification.
Fixes https://github.com/nodejs/nodejs.dev/issues/2736

fix(css): minified html and include css on load

---

package-lock.json

chore: Update dependencies in package-lock.json

---

content/learn/command-line/node-cli-args.en.md
content/learn/getting-started/node-installation.en.md
util-node/createLearnQuery.js
util-node/createPageUtils.js

This PR fixes https://github.com/nodejs/nodejs.dev/issues/2799 and fixes the "issue" of links not being automatically locale prefixed, due to using `https://nodejs.dev` as base url.
- Closes https://github.com/nodejs/nodejs.dev/issues/2799

fix(learn): fixes links to use path prefix calculation

---

src/util/__tests__/dateIsBetween.test.ts

Added unit tests for dateIsBetween function in util.
directory :- /src/util/__test__/ 
Add total 6 new unit tests.
Related to #2744

test(util): add test for dateIsBetween in util

---

src/util/__tests__/getAgeInYears.test.ts

Added unit tests for getAgeInYears function in util.
Total 7 tests added.
Related #2744

test(util): add test for getAgeInYears in util

---

src/util/__tests__/detectLanguage.test.ts

Added unit tests for detectLanguage function in util
Related #2744

test(util): add test for detectLanguage in util

---

firebase.json
redirects.js

A lot of broken links exist now. This is a fix for some of them. More PR's are needed. This could be a good hacktoberfest fix.

fix: 🐛 redirect old links to /en/learn

---

src/components/Codebox/index.tsx

This PR fixes a little display bug when showing CodeBox labels

fix(codebox): normalise display languages

---

firebase.json
gatsby-config.js
package-lock.json
package.json
redirects.js

This PR updates dependency and removes our `offline` (service-worker) package as it was unreliable and not really caching pages correctly when on offline mode.

chore(dependencies): updated dependencies, removed sw

---

src/util/__tests__/getUpcomingReleases.test.ts

Added test for function `getUpcomingReleases`.
#2744

test(getUpcomingReleases): add test

---

src/pages/index.module.scss

Signed-off-by: Claudio Wunder <cwunder@gnome.org>
This PR simply fixes the grid template columns for the node.js features of home page.
- Closes https://github.com/nodejs/nodejs.dev/issues/2945

fix(grid): fixed feature columns alignment

---

content/learn/getting-started/node-with-typescript.en.md

Fix a grammar issue where two independent clauses were joined by a comma.
Signed-off-by: Daniel Schroeder <DanielSchroederDev@gmail.com>

Update Node with TypeScript docs

---

content/learn/getting-started/node-with-typescript.en.md

I ran a few of the awkwardly worded sentences through my Grammarly extension to clean them up a bit. 
Signed-off-by: Daniel Schroeder <DanielSchroederDev@gmail.com>

Fix grammar issues

---

src/i18n/locales/fr.json

* Fix typo of French translation
#3001 

Fix(header): I18n French

---

src/i18n/locales/fr.json

* "components.downloadToggle.recommendation"
No related issues

feat(i18n fr) fix missed translation of site

---

content/learn/manipulating-files/node-writing-files.en.md

Signed-off-by: Maitray Bhardwaj <maitraybhardwaj@gmail.com>
Changed "Wiriting" to "Writing"

fix: Fixed typo

---

src/util/isAbsoluteUrl.ts

This PR fixes an issue regarding the `isAbsoluteUrl` utility

fix(absolute-url): fix absolute url util

---

.github/workflows/firebase-deployment.yml

maybe a fix for our deployment issue

---

content/about/security.en.md
content/about/security.fr.md
content/learn/command-line/node-run-cli.fr.md
content/learn/getting-started/node-es6.fr.md
content/learn/getting-started/node-with-typescript.fr.md
content/learn/getting-started/node-with-web-assembly.fr.md
content/learn/getting-started/npm.fr.md
content/learn/manipulating-files/node-file-descriptors.fr.md
content/learn/manipulating-files/node-file-paths.fr.md
content/learn/manipulating-files/node-folders.fr.md

* Fix authors typo
* I18n missed original author
No related Issues

Fix(authors)

---

src/navigations/learn.module.scss
src/navigations/learn.tsx
src/templates/__tests__/__snapshots__/learn.test.tsx.snap
src/types/navigation.ts

Marked learn section title as read with a checkmark if all subsections are read.
[Screencast.webm](https://user-images.githubusercontent.com/42532987/208301529-fa9e3b8b-d02b-4ad1-8d65-cdc6eabf116b.webm)
Resolves #3097 

feat(Learn): mark learn section title as read

---

README.md

I would like to join the team, help maintain the docs and contribute more to it 🚀.
You can find my contributions [here](https://github.com/nodejs/nodejs.dev/commits?author=shanpriyan)

chore: add @shanpriyan to current team

---

README.md
content/learn/asynchronous-work/node-process-nexttick.en.md
content/learn/asynchronous-work/node-process-nexttick.fr.md

Add a code example of event loop process order on node-process-nexttick.en page. Console logs showing the code snippet and the output detailing the order of execution
Closes #3106

Provide a code example of event loop process order on node-process-nexttick learn page

---

content/learn/asynchronous-work/blocking-vs-non-blocking.en.md
content/learn/asynchronous-work/blocking-vs-non-blocking.fr.md

[#4875](https://github.com/nodejs/nodejs.org/issues/4875) in [nodejs.org](https://github.com/nodejs/nodejs.org)

docs(Learn): remove `About Node.js` page link from additional resources

---

src/components/ArticleComponents/Codebox/index.tsx

`parsedLangauge` -> `parsedLanguage`
No related issues

Fix(code grammar): codebox component

---

content/learn/getting-started/node-introduction.en.md

Signed-off-by: Augustin Mauroy <97875033+AugustinMauroy@users.noreply.github.com>
remove unused "-->"

chore(learn): remove unused "-->"

---

content/download/releases.pt.md
content/get-involved/collab-summit.pt.md
content/get-involved/contribute.pt.md
content/get-involved/index.pt.md
src/components/CommonComponents/Hero/index.module.scss
src/i18n/locales/pt.json

In this pull request, I am sending one more updates to the portuguese
content of the website, it consists of new translated documents so I
believe it will be quick to review and apply the changes.

docs(pt): update and translate new content to portuguese

---

content/about/about.pt.md
content/about/governance.pt.md
content/about/releases.pt.md
content/about/resources.pt.md
content/about/security.pt.md
content/download/package-manager.pt.md
content/learn/getting-started/node-difference-browser.pt.md
content/learn/getting-started/node-difference-dev-prod.pt.md
content/learn/getting-started/node-installation.pt.md
content/learn/getting-started/node-introduction.pt.md
src/i18n/locales/pt.json

In this pull request, I am concluding the translation of `download` folder,
and then I am sending the translation of the entire `about` folder.
Next, I will be sending the translations of the contents inside `learn` folder.
- [ x I have run `npm run test` to check if all tests are passing, and/or `npm run test -- -u` to update snapshots if I created and/or updated React Components.

docs(pt): translate the `content/about` folder to portuguese

---

content/learn/asynchronous-work/node-process-nexttick.en.md

Changed the invocation sequence of setTimeout , setImmediate  and output logs to maintain output numbering order. ie. 1 -> 2 -> 3 -> 4.

docs: Updated node-process-nexttick.en.md 
